// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/chunked.dart';
import 'api/client.dart';
import 'api/encrypted.dart';
import 'api/error.dart';
import 'api/forest.dart';
import 'api/multipart.dart';
import 'api/rotation.dart';
import 'api/sharing.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_AcceptedShareHandlePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_EncryptedClientHandlePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_FulaClientHandlePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_MultipartHandlePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_RotationManagerHandlePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AcceptedShareHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          dynamic raw);

  @protected
  EncryptedClientHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          dynamic raw);

  @protected
  FulaClientHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          dynamic raw);

  @protected
  MultipartHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          dynamic raw);

  @protected
  RotationManagerHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          dynamic raw);

  @protected
  AcceptedShareHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          dynamic raw);

  @protected
  EncryptedClientHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          dynamic raw);

  @protected
  FulaClientHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          dynamic raw);

  @protected
  MultipartHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          dynamic raw);

  @protected
  RotationManagerHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          dynamic raw);

  @protected
  AcceptedShareHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          dynamic raw);

  @protected
  EncryptedClientHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          dynamic raw);

  @protected
  FulaClientHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          dynamic raw);

  @protected
  MultipartHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          dynamic raw);

  @protected
  RotationManagerHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  EncryptionConfig dco_decode_box_autoadd_encryption_config(dynamic raw);

  @protected
  FulaConfig dco_decode_box_autoadd_fula_config(dynamic raw);

  @protected
  FulaError dco_decode_box_autoadd_fula_error(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ListOptions dco_decode_box_autoadd_list_options(dynamic raw);

  @protected
  ObjectMetadata dco_decode_box_autoadd_object_metadata(dynamic raw);

  @protected
  PinningConfig dco_decode_box_autoadd_pinning_config(dynamic raw);

  @protected
  RotationReport dco_decode_box_autoadd_rotation_report(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BucketInfo dco_decode_bucket_info(dynamic raw);

  @protected
  CopyResult dco_decode_copy_result(dynamic raw);

  @protected
  DecryptedObjectInfo dco_decode_decrypted_object_info(dynamic raw);

  @protected
  DirectoryEntry dco_decode_directory_entry(dynamic raw);

  @protected
  DirectoryListing dco_decode_directory_listing(dynamic raw);

  @protected
  EncryptionConfig dco_decode_encryption_config(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FileMetadata dco_decode_file_metadata(dynamic raw);

  @protected
  ForestSubtree dco_decode_forest_subtree(dynamic raw);

  @protected
  FulaConfig dco_decode_fula_config(dynamic raw);

  @protected
  FulaError dco_decode_fula_error(dynamic raw);

  @protected
  GetObjectResult dco_decode_get_object_result(dynamic raw);

  @protected
  HeadResult dco_decode_head_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BucketInfo> dco_decode_list_bucket_info(dynamic raw);

  @protected
  List<DirectoryEntry> dco_decode_list_directory_entry(dynamic raw);

  @protected
  List<FileMetadata> dco_decode_list_file_metadata(dynamic raw);

  @protected
  List<MetadataEntry> dco_decode_list_metadata_entry(dynamic raw);

  @protected
  List<ObjectInfo> dco_decode_list_object_info(dynamic raw);

  @protected
  ListObjectsResult dco_decode_list_objects_result(dynamic raw);

  @protected
  ListOptions dco_decode_list_options(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RotationFailure> dco_decode_list_rotation_failure(dynamic raw);

  @protected
  MetadataEntry dco_decode_metadata_entry(dynamic raw);

  @protected
  ObfuscationMode dco_decode_obfuscation_mode(dynamic raw);

  @protected
  ObjectInfo dco_decode_object_info(dynamic raw);

  @protected
  ObjectMetadata dco_decode_object_metadata(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PinningConfig dco_decode_pinning_config(dynamic raw);

  @protected
  PutResult dco_decode_put_result(dynamic raw);

  @protected
  RotationFailure dco_decode_rotation_failure(dynamic raw);

  @protected
  RotationReport dco_decode_rotation_report(dynamic raw);

  @protected
  ShareMode dco_decode_share_mode(dynamic raw);

  @protected
  SharePermissions dco_decode_share_permissions(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UploadProgress dco_decode_upload_progress(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AcceptedShareHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          SseDeserializer deserializer);

  @protected
  EncryptedClientHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          SseDeserializer deserializer);

  @protected
  FulaClientHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          SseDeserializer deserializer);

  @protected
  MultipartHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          SseDeserializer deserializer);

  @protected
  RotationManagerHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          SseDeserializer deserializer);

  @protected
  AcceptedShareHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          SseDeserializer deserializer);

  @protected
  EncryptedClientHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          SseDeserializer deserializer);

  @protected
  FulaClientHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          SseDeserializer deserializer);

  @protected
  MultipartHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          SseDeserializer deserializer);

  @protected
  RotationManagerHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          SseDeserializer deserializer);

  @protected
  AcceptedShareHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          SseDeserializer deserializer);

  @protected
  EncryptedClientHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          SseDeserializer deserializer);

  @protected
  FulaClientHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          SseDeserializer deserializer);

  @protected
  MultipartHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          SseDeserializer deserializer);

  @protected
  RotationManagerHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  EncryptionConfig sse_decode_box_autoadd_encryption_config(
      SseDeserializer deserializer);

  @protected
  FulaConfig sse_decode_box_autoadd_fula_config(SseDeserializer deserializer);

  @protected
  FulaError sse_decode_box_autoadd_fula_error(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ListOptions sse_decode_box_autoadd_list_options(SseDeserializer deserializer);

  @protected
  ObjectMetadata sse_decode_box_autoadd_object_metadata(
      SseDeserializer deserializer);

  @protected
  PinningConfig sse_decode_box_autoadd_pinning_config(
      SseDeserializer deserializer);

  @protected
  RotationReport sse_decode_box_autoadd_rotation_report(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BucketInfo sse_decode_bucket_info(SseDeserializer deserializer);

  @protected
  CopyResult sse_decode_copy_result(SseDeserializer deserializer);

  @protected
  DecryptedObjectInfo sse_decode_decrypted_object_info(
      SseDeserializer deserializer);

  @protected
  DirectoryEntry sse_decode_directory_entry(SseDeserializer deserializer);

  @protected
  DirectoryListing sse_decode_directory_listing(SseDeserializer deserializer);

  @protected
  EncryptionConfig sse_decode_encryption_config(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FileMetadata sse_decode_file_metadata(SseDeserializer deserializer);

  @protected
  ForestSubtree sse_decode_forest_subtree(SseDeserializer deserializer);

  @protected
  FulaConfig sse_decode_fula_config(SseDeserializer deserializer);

  @protected
  FulaError sse_decode_fula_error(SseDeserializer deserializer);

  @protected
  GetObjectResult sse_decode_get_object_result(SseDeserializer deserializer);

  @protected
  HeadResult sse_decode_head_result(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BucketInfo> sse_decode_list_bucket_info(SseDeserializer deserializer);

  @protected
  List<DirectoryEntry> sse_decode_list_directory_entry(
      SseDeserializer deserializer);

  @protected
  List<FileMetadata> sse_decode_list_file_metadata(
      SseDeserializer deserializer);

  @protected
  List<MetadataEntry> sse_decode_list_metadata_entry(
      SseDeserializer deserializer);

  @protected
  List<ObjectInfo> sse_decode_list_object_info(SseDeserializer deserializer);

  @protected
  ListObjectsResult sse_decode_list_objects_result(
      SseDeserializer deserializer);

  @protected
  ListOptions sse_decode_list_options(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RotationFailure> sse_decode_list_rotation_failure(
      SseDeserializer deserializer);

  @protected
  MetadataEntry sse_decode_metadata_entry(SseDeserializer deserializer);

  @protected
  ObfuscationMode sse_decode_obfuscation_mode(SseDeserializer deserializer);

  @protected
  ObjectInfo sse_decode_object_info(SseDeserializer deserializer);

  @protected
  ObjectMetadata sse_decode_object_metadata(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PinningConfig sse_decode_pinning_config(SseDeserializer deserializer);

  @protected
  PutResult sse_decode_put_result(SseDeserializer deserializer);

  @protected
  RotationFailure sse_decode_rotation_failure(SseDeserializer deserializer);

  @protected
  RotationReport sse_decode_rotation_report(SseDeserializer deserializer);

  @protected
  ShareMode sse_decode_share_mode(SseDeserializer deserializer);

  @protected
  SharePermissions sse_decode_share_permissions(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UploadProgress sse_decode_upload_progress(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_encryption_config(EncryptionConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_encryption_config(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_fula_config(FulaConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_fula_config(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_fula_error(FulaError raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_fula_error(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_list_options(ListOptions raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_options(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_object_metadata(ObjectMetadata raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_object_metadata(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_pinning_config(PinningConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_pinning_config(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_rotation_report(RotationReport raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_rotation_report(raw);
  }

  @protected
  int cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_32(raw);
  }

  @protected
  JSAny cst_encode_bucket_info(BucketInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.name), cst_encode_i_64(raw.createdAt)]
        .jsify()!;
  }

  @protected
  JSAny cst_encode_copy_result(CopyResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.etag), cst_encode_i_64(raw.lastModified)]
        .jsify()!;
  }

  @protected
  JSAny cst_encode_decrypted_object_info(DecryptedObjectInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.data),
      cst_encode_String(raw.originalKey),
      cst_encode_u_64(raw.size),
      cst_encode_opt_String(raw.contentType),
      cst_encode_list_metadata_entry(raw.metadata)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_directory_entry(DirectoryEntry raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.name),
      cst_encode_bool(raw.isDirectory),
      cst_encode_list_file_metadata(raw.files)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_directory_listing(DirectoryListing raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.bucket),
      cst_encode_opt_String(raw.prefix),
      cst_encode_list_directory_entry(raw.entries)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_encryption_config(EncryptionConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_list_prim_u_8_strict(raw.secretKey),
      cst_encode_bool(raw.enableMetadataPrivacy),
      cst_encode_obfuscation_mode(raw.obfuscationMode)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_file_metadata(FileMetadata raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.storageKey),
      cst_encode_String(raw.originalKey),
      cst_encode_u_64(raw.size),
      cst_encode_opt_String(raw.contentType),
      cst_encode_opt_box_autoadd_i_64(raw.createdAt),
      cst_encode_opt_box_autoadd_i_64(raw.modifiedAt),
      cst_encode_bool(raw.isEncrypted)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_forest_subtree(ForestSubtree raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_list_prim_u_8_strict(raw.serialized)].jsify()!;
  }

  @protected
  JSAny cst_encode_fula_config(FulaConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.endpoint),
      cst_encode_opt_String(raw.accessToken),
      cst_encode_u_64(raw.timeoutSeconds),
      cst_encode_u_32(raw.maxRetries)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_fula_error(FulaError raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is FulaError_Network) {
      return [0, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_NotFound) {
      return [1, cst_encode_String(raw.bucket), cst_encode_String(raw.key)]
          .jsify()!;
    }
    if (raw is FulaError_BucketNotFound) {
      return [2, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_AccessDenied) {
      return [3, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_Encryption) {
      return [4, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_InvalidConfig) {
      return [5, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_UploadFailed) {
      return [6, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_DownloadFailed) {
      return [7, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_XmlParse) {
      return [8, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_InvalidResponse) {
      return [9, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_ShareError) {
      return [10, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_RotationError) {
      return [11, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_ForestError) {
      return [12, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is FulaError_Internal) {
      return [13, cst_encode_String(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_get_object_result(GetObjectResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.data),
      cst_encode_String(raw.etag),
      cst_encode_opt_String(raw.contentType),
      cst_encode_u_64(raw.size),
      cst_encode_i_64(raw.lastModified),
      cst_encode_list_metadata_entry(raw.metadata)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_head_result(HeadResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.etag),
      cst_encode_opt_String(raw.contentType),
      cst_encode_u_64(raw.size),
      cst_encode_i_64(raw.lastModified),
      cst_encode_list_metadata_entry(raw.metadata)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_bucket_info(List<BucketInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_bucket_info).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_directory_entry(List<DirectoryEntry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_directory_entry).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_file_metadata(List<FileMetadata> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_file_metadata).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_metadata_entry(List<MetadataEntry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_metadata_entry).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_object_info(List<ObjectInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_object_info).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_objects_result(ListObjectsResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_object_info(raw.objects),
      cst_encode_list_String(raw.commonPrefixes),
      cst_encode_bool(raw.isTruncated),
      cst_encode_opt_String(raw.nextToken)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_options(ListOptions raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_String(raw.prefix),
      cst_encode_opt_String(raw.delimiter),
      cst_encode_opt_box_autoadd_u_32(raw.maxKeys),
      cst_encode_opt_String(raw.continuationToken)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_rotation_failure(List<RotationFailure> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_rotation_failure).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_metadata_entry(MetadataEntry raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.key), cst_encode_String(raw.value)].jsify()!;
  }

  @protected
  JSAny cst_encode_object_info(ObjectInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.key),
      cst_encode_u_64(raw.size),
      cst_encode_i_64(raw.lastModified),
      cst_encode_String(raw.etag),
      cst_encode_String(raw.storageClass)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_object_metadata(ObjectMetadata raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_String(raw.contentType),
      cst_encode_opt_String(raw.cacheControl),
      cst_encode_list_metadata_entry(raw.userMetadata)
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  JSAny? cst_encode_opt_list_prim_u_8_strict(Uint8List? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_list_prim_u_8_strict(raw);
  }

  @protected
  JSAny cst_encode_pinning_config(PinningConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.endpoint), cst_encode_String(raw.token)]
        .jsify()!;
  }

  @protected
  JSAny cst_encode_put_result(PutResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.etag), cst_encode_opt_String(raw.versionId)]
        .jsify()!;
  }

  @protected
  JSAny cst_encode_rotation_failure(RotationFailure raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.storageKey), cst_encode_String(raw.error)]
        .jsify()!;
  }

  @protected
  JSAny cst_encode_rotation_report(RotationReport raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_32(raw.total),
      cst_encode_u_32(raw.rotated),
      cst_encode_u_32(raw.skipped),
      cst_encode_u_32(raw.failed),
      cst_encode_list_rotation_failure(raw.failures)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_share_permissions(SharePermissions raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.canRead),
      cst_encode_bool(raw.canWrite),
      cst_encode_opt_box_autoadd_i_64(raw.expiresAt)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_upload_progress(UploadProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_64(raw.bytesUploaded),
      cst_encode_u_64(raw.totalBytes),
      cst_encode_u_32(raw.currentPart),
      cst_encode_u_32(raw.totalParts),
      cst_encode_f_64(raw.percentage)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
      AcceptedShareHandle raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
      EncryptedClientHandle raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
      FulaClientHandle raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
      MultipartHandle raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
      RotationManagerHandle raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
      AcceptedShareHandle raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
      EncryptedClientHandle raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
      FulaClientHandle raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
      MultipartHandle raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
      RotationManagerHandle raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
      AcceptedShareHandle raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
      EncryptedClientHandle raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
      FulaClientHandle raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
      MultipartHandle raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
      RotationManagerHandle raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_obfuscation_mode(ObfuscationMode raw);

  @protected
  int cst_encode_share_mode(ShareMode raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          AcceptedShareHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          EncryptedClientHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          FulaClientHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          MultipartHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          RotationManagerHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          AcceptedShareHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          EncryptedClientHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          FulaClientHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          MultipartHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          RotationManagerHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          AcceptedShareHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          EncryptedClientHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          FulaClientHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          MultipartHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          RotationManagerHandle self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_encryption_config(
      EncryptionConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fula_config(
      FulaConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fula_error(
      FulaError self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_list_options(
      ListOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_object_metadata(
      ObjectMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pinning_config(
      PinningConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rotation_report(
      RotationReport self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bucket_info(BucketInfo self, SseSerializer serializer);

  @protected
  void sse_encode_copy_result(CopyResult self, SseSerializer serializer);

  @protected
  void sse_encode_decrypted_object_info(
      DecryptedObjectInfo self, SseSerializer serializer);

  @protected
  void sse_encode_directory_entry(
      DirectoryEntry self, SseSerializer serializer);

  @protected
  void sse_encode_directory_listing(
      DirectoryListing self, SseSerializer serializer);

  @protected
  void sse_encode_encryption_config(
      EncryptionConfig self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_file_metadata(FileMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_forest_subtree(ForestSubtree self, SseSerializer serializer);

  @protected
  void sse_encode_fula_config(FulaConfig self, SseSerializer serializer);

  @protected
  void sse_encode_fula_error(FulaError self, SseSerializer serializer);

  @protected
  void sse_encode_get_object_result(
      GetObjectResult self, SseSerializer serializer);

  @protected
  void sse_encode_head_result(HeadResult self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bucket_info(
      List<BucketInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_directory_entry(
      List<DirectoryEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_metadata(
      List<FileMetadata> self, SseSerializer serializer);

  @protected
  void sse_encode_list_metadata_entry(
      List<MetadataEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_object_info(
      List<ObjectInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_objects_result(
      ListObjectsResult self, SseSerializer serializer);

  @protected
  void sse_encode_list_options(ListOptions self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_rotation_failure(
      List<RotationFailure> self, SseSerializer serializer);

  @protected
  void sse_encode_metadata_entry(MetadataEntry self, SseSerializer serializer);

  @protected
  void sse_encode_obfuscation_mode(
      ObfuscationMode self, SseSerializer serializer);

  @protected
  void sse_encode_object_info(ObjectInfo self, SseSerializer serializer);

  @protected
  void sse_encode_object_metadata(
      ObjectMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_pinning_config(PinningConfig self, SseSerializer serializer);

  @protected
  void sse_encode_put_result(PutResult self, SseSerializer serializer);

  @protected
  void sse_encode_rotation_failure(
      RotationFailure self, SseSerializer serializer);

  @protected
  void sse_encode_rotation_report(
      RotationReport self, SseSerializer serializer);

  @protected
  void sse_encode_share_mode(ShareMode self, SseSerializer serializer);

  @protected
  void sse_encode_share_permissions(
      SharePermissions self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_upload_progress(
      UploadProgress self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__multipart__abort_multipart(
          NativePortType port_, int handle) =>
      wasmModule.wire__crate__api__multipart__abort_multipart(port_, handle);

  void wire__crate__api__sharing__accept_share(
          NativePortType port_, int client, String token_json) =>
      wasmModule.wire__crate__api__sharing__accept_share(
          port_, client, token_json);

  void wire__crate__api__client__bucket_exists(
          NativePortType port_, int client, String name) =>
      wasmModule.wire__crate__api__client__bucket_exists(port_, client, name);

  void wire__crate__api__multipart__complete_multipart(
          NativePortType port_, int handle) =>
      wasmModule.wire__crate__api__multipart__complete_multipart(port_, handle);

  void wire__crate__api__client__copy_object(
          NativePortType port_,
          int client,
          String src_bucket,
          String src_key,
          String dst_bucket,
          String dst_key) =>
      wasmModule.wire__crate__api__client__copy_object(
          port_, client, src_bucket, src_key, dst_bucket, dst_key);

  void wire__crate__api__client__create_bucket(
          NativePortType port_, int client, String name) =>
      wasmModule.wire__crate__api__client__create_bucket(port_, client, name);

  void wire__crate__api__client__create_client(
          NativePortType port_, JSAny config) =>
      wasmModule.wire__crate__api__client__create_client(port_, config);

  void wire__crate__api__client__create_encrypted_client(
          NativePortType port_, JSAny config, JSAny encryption) =>
      wasmModule.wire__crate__api__client__create_encrypted_client(
          port_, config, encryption);

  void wire__crate__api__client__create_encrypted_client_with_pinning(
          NativePortType port_,
          JSAny config,
          JSAny encryption,
          JSAny pinning) =>
      wasmModule.wire__crate__api__client__create_encrypted_client_with_pinning(
          port_, config, encryption, pinning);

  void wire__crate__api__rotation__create_rotation_manager(
          NativePortType port_, int client) =>
      wasmModule.wire__crate__api__rotation__create_rotation_manager(
          port_, client);

  void wire__crate__api__sharing__create_share_token(
          NativePortType port_,
          int client,
          String storage_key,
          JSAny recipient_public_key,
          JSAny? expires_at) =>
      wasmModule.wire__crate__api__sharing__create_share_token(
          port_, client, storage_key, recipient_public_key, expires_at);

  void wire__crate__api__sharing__create_share_token_with_mode(
          NativePortType port_,
          int client,
          String storage_key,
          JSAny recipient_public_key,
          int mode,
          JSAny? expires_at) =>
      wasmModule.wire__crate__api__sharing__create_share_token_with_mode(
          port_, client, storage_key, recipient_public_key, mode, expires_at);

  void wire__crate__api__client__delete_bucket(
          NativePortType port_, int client, String name) =>
      wasmModule.wire__crate__api__client__delete_bucket(port_, client, name);

  void wire__crate__api__encrypted__delete_by_storage_key(NativePortType port_,
          int client, String bucket, String storage_key) =>
      wasmModule.wire__crate__api__encrypted__delete_by_storage_key(
          port_, client, bucket, storage_key);

  void wire__crate__api__encrypted__delete_encrypted(
          NativePortType port_, int client, String bucket, String key) =>
      wasmModule.wire__crate__api__encrypted__delete_encrypted(
          port_, client, bucket, key);

  void wire__crate__api__forest__delete_flat(
          NativePortType port_, int client, String bucket, String path) =>
      wasmModule.wire__crate__api__forest__delete_flat(
          port_, client, bucket, path);

  void wire__crate__api__client__delete_object(
          NativePortType port_, int client, String bucket, String key) =>
      wasmModule.wire__crate__api__client__delete_object(
          port_, client, bucket, key);

  void wire__crate__api__encrypted__enc_create_bucket(
          NativePortType port_, int client, String name) =>
      wasmModule.wire__crate__api__encrypted__enc_create_bucket(
          port_, client, name);

  void wire__crate__api__encrypted__enc_delete_bucket(
          NativePortType port_, int client, String name) =>
      wasmModule.wire__crate__api__encrypted__enc_delete_bucket(
          port_, client, name);

  void wire__crate__api__encrypted__enc_list_buckets(
          NativePortType port_, int client) =>
      wasmModule.wire__crate__api__encrypted__enc_list_buckets(port_, client);

  void wire__crate__api__types__encryption_config_default(
          NativePortType port_) =>
      wasmModule.wire__crate__api__types__encryption_config_default(port_);

  void wire__crate__api__encrypted__export_secret_key(
          NativePortType port_, int client) =>
      wasmModule.wire__crate__api__encrypted__export_secret_key(port_, client);

  void wire__crate__api__forest__flush_forest(
          NativePortType port_, int client, String bucket) =>
      wasmModule.wire__crate__api__forest__flush_forest(port_, client, bucket);

  void wire__crate__api__types__fula_config_default(NativePortType port_) =>
      wasmModule.wire__crate__api__types__fula_config_default(port_);

  void wire__crate__api__error__fula_error_error_code(
          NativePortType port_, JSAny that) =>
      wasmModule.wire__crate__api__error__fula_error_error_code(port_, that);

  void wire__crate__api__error__fula_error_is_access_denied(
          NativePortType port_, JSAny that) =>
      wasmModule.wire__crate__api__error__fula_error_is_access_denied(
          port_, that);

  void wire__crate__api__error__fula_error_is_encryption_error(
          NativePortType port_, JSAny that) =>
      wasmModule.wire__crate__api__error__fula_error_is_encryption_error(
          port_, that);

  void wire__crate__api__error__fula_error_is_network_error(
          NativePortType port_, JSAny that) =>
      wasmModule.wire__crate__api__error__fula_error_is_network_error(
          port_, that);

  void wire__crate__api__error__fula_error_is_not_found(
          NativePortType port_, JSAny that) =>
      wasmModule.wire__crate__api__error__fula_error_is_not_found(port_, that);

  void wire__crate__api__chunked__get_chunked(
          NativePortType port_, int client, String bucket, String key) =>
      wasmModule.wire__crate__api__chunked__get_chunked(
          port_, client, bucket, key);

  void wire__crate__api__multipart__get_completed_parts(
          NativePortType port_, int handle) =>
      wasmModule.wire__crate__api__multipart__get_completed_parts(
          port_, handle);

  void wire__crate__api__encrypted__get_decrypted(
          NativePortType port_, int client, String bucket, String key) =>
      wasmModule.wire__crate__api__encrypted__get_decrypted(
          port_, client, bucket, key);

  void wire__crate__api__encrypted__get_decrypted_by_storage_key(
          NativePortType port_,
          int client,
          String bucket,
          String storage_key) =>
      wasmModule.wire__crate__api__encrypted__get_decrypted_by_storage_key(
          port_, client, bucket, storage_key);

  void wire__crate__api__forest__get_flat(
          NativePortType port_, int client, String bucket, String path) =>
      wasmModule.wire__crate__api__forest__get_flat(
          port_, client, bucket, path);

  void wire__crate__api__forest__get_forest_subtree(
          NativePortType port_, int client, String bucket, String prefix) =>
      wasmModule.wire__crate__api__forest__get_forest_subtree(
          port_, client, bucket, prefix);

  void wire__crate__api__rotation__get_kek_version(NativePortType port_,
          int client, String bucket, String storage_key) =>
      wasmModule.wire__crate__api__rotation__get_kek_version(
          port_, client, bucket, storage_key);

  void wire__crate__api__client__get_object(
          NativePortType port_, int client, String bucket, String key) =>
      wasmModule.wire__crate__api__client__get_object(
          port_, client, bucket, key);

  void wire__crate__api__client__get_object_with_metadata(
          NativePortType port_, int client, String bucket, String key) =>
      wasmModule.wire__crate__api__client__get_object_with_metadata(
          port_, client, bucket, key);

  void wire__crate__api__encrypted__get_public_key(
          NativePortType port_, int client) =>
      wasmModule.wire__crate__api__encrypted__get_public_key(port_, client);

  void wire__crate__api__chunked__get_range(NativePortType port_, int client,
          String bucket, String key, JSAny offset, JSAny length) =>
      wasmModule.wire__crate__api__chunked__get_range(
          port_, client, bucket, key, offset, length);

  void wire__crate__api__sharing__get_share_permissions(
          NativePortType port_, int share) =>
      wasmModule.wire__crate__api__sharing__get_share_permissions(port_, share);

  void wire__crate__api__multipart__get_upload_id(
          NativePortType port_, int handle) =>
      wasmModule.wire__crate__api__multipart__get_upload_id(port_, handle);

  void wire__crate__api__encrypted__get_with_private_metadata(
          NativePortType port_,
          int client,
          String bucket,
          String storage_key) =>
      wasmModule.wire__crate__api__encrypted__get_with_private_metadata(
          port_, client, bucket, storage_key);

  void wire__crate__api__sharing__get_with_share(NativePortType port_,
          int client, String bucket, String storage_key, int share) =>
      wasmModule.wire__crate__api__sharing__get_with_share(
          port_, client, bucket, storage_key, share);

  void wire__crate__api__sharing__get_with_token(NativePortType port_,
          int client, String bucket, String storage_key, String token_json) =>
      wasmModule.wire__crate__api__sharing__get_with_token(
          port_, client, bucket, storage_key, token_json);

  void wire__crate__api__forest__has_pending_changes(
          NativePortType port_, int client, String bucket) =>
      wasmModule.wire__crate__api__forest__has_pending_changes(
          port_, client, bucket);

  void wire__crate__api__encrypted__head_decrypted(NativePortType port_,
          int client, String bucket, String storage_key) =>
      wasmModule.wire__crate__api__encrypted__head_decrypted(
          port_, client, bucket, storage_key);

  void wire__crate__api__client__head_object(
          NativePortType port_, int client, String bucket, String key) =>
      wasmModule.wire__crate__api__client__head_object(
          port_, client, bucket, key);

  void wire__crate__api__encrypted__is_flat_namespace(
          NativePortType port_, int client) =>
      wasmModule.wire__crate__api__encrypted__is_flat_namespace(port_, client);

  void wire__crate__api__sharing__is_share_expired(
          NativePortType port_, int share) =>
      wasmModule.wire__crate__api__sharing__is_share_expired(port_, share);

  void wire__crate__api__client__list_buckets(
          NativePortType port_, int client) =>
      wasmModule.wire__crate__api__client__list_buckets(port_, client);

  void wire__crate__api__encrypted__list_decrypted(
          NativePortType port_, int client, String bucket, JSAny options) =>
      wasmModule.wire__crate__api__encrypted__list_decrypted(
          port_, client, bucket, options);

  void wire__crate__api__encrypted__list_directory(
          NativePortType port_, int client, String bucket, String? prefix) =>
      wasmModule.wire__crate__api__encrypted__list_directory(
          port_, client, bucket, prefix);

  void wire__crate__api__forest__list_from_forest(
          NativePortType port_, int client, String bucket) =>
      wasmModule.wire__crate__api__forest__list_from_forest(
          port_, client, bucket);

  void wire__crate__api__client__list_objects(
          NativePortType port_, int client, String bucket, JSAny options) =>
      wasmModule.wire__crate__api__client__list_objects(
          port_, client, bucket, options);

  void wire__crate__api__types__list_options_default(NativePortType port_) =>
      wasmModule.wire__crate__api__types__list_options_default(port_);

  void wire__crate__api__forest__load_forest(
          NativePortType port_, int client, String bucket) =>
      wasmModule.wire__crate__api__forest__load_forest(port_, client, bucket);

  void wire__crate__api__types__obfuscation_mode_default(
          NativePortType port_) =>
      wasmModule.wire__crate__api__types__obfuscation_mode_default(port_);

  void wire__crate__api__client__object_exists(
          NativePortType port_, int client, String bucket, String key) =>
      wasmModule.wire__crate__api__client__object_exists(
          port_, client, bucket, key);

  void wire__crate__api__types__object_metadata_default(NativePortType port_) =>
      wasmModule.wire__crate__api__types__object_metadata_default(port_);

  void wire__crate__api__chunked__put_chunked(NativePortType port_, int client,
          String bucket, String key, JSAny data, int? chunk_size) =>
      wasmModule.wire__crate__api__chunked__put_chunked(
          port_, client, bucket, key, data, chunk_size);

  void wire__crate__api__encrypted__put_encrypted(NativePortType port_,
          int client, String bucket, String key, JSAny data) =>
      wasmModule.wire__crate__api__encrypted__put_encrypted(
          port_, client, bucket, key, data);

  void wire__crate__api__encrypted__put_encrypted_with_type(
          NativePortType port_,
          int client,
          String bucket,
          String key,
          JSAny data,
          String content_type) =>
      wasmModule.wire__crate__api__encrypted__put_encrypted_with_type(
          port_, client, bucket, key, data, content_type);

  void wire__crate__api__forest__put_flat(NativePortType port_, int client,
          String bucket, String path, JSAny data, String? content_type) =>
      wasmModule.wire__crate__api__forest__put_flat(
          port_, client, bucket, path, data, content_type);

  void wire__crate__api__forest__put_flat_deferred(
          NativePortType port_,
          int client,
          String bucket,
          String path,
          JSAny data,
          String? content_type) =>
      wasmModule.wire__crate__api__forest__put_flat_deferred(
          port_, client, bucket, path, data, content_type);

  void wire__crate__api__client__put_object(NativePortType port_, int client,
          String bucket, String key, JSAny data) =>
      wasmModule.wire__crate__api__client__put_object(
          port_, client, bucket, key, data);

  void wire__crate__api__client__put_object_with_metadata(NativePortType port_,
          int client, String bucket, String key, JSAny data, JSAny metadata) =>
      wasmModule.wire__crate__api__client__put_object_with_metadata(
          port_, client, bucket, key, data, metadata);

  void wire__crate__api__rotation__rewrap_object(NativePortType port_,
          int client, String bucket, String storage_key, int manager) =>
      wasmModule.wire__crate__api__rotation__rewrap_object(
          port_, client, bucket, storage_key, manager);

  void wire__crate__api__rotation__rotate_bucket(
          NativePortType port_, int client, String bucket, int manager) =>
      wasmModule.wire__crate__api__rotation__rotate_bucket(
          port_, client, bucket, manager);

  void wire__crate__api__types__rotation_report_is_success(
          NativePortType port_, JSAny that) =>
      wasmModule.wire__crate__api__types__rotation_report_is_success(
          port_, that);

  void wire__crate__api__types__rotation_report_success_rate(
          NativePortType port_, JSAny that) =>
      wasmModule.wire__crate__api__types__rotation_report_success_rate(
          port_, that);

  void wire__crate__api__forest__save_forest(
          NativePortType port_, int client, String bucket) =>
      wasmModule.wire__crate__api__forest__save_forest(port_, client, bucket);

  void wire__crate__api__chunked__should_use_chunked(
          NativePortType port_, JSAny size) =>
      wasmModule.wire__crate__api__chunked__should_use_chunked(port_, size);

  void wire__crate__api__multipart__start_multipart(
          NativePortType port_, int client, String bucket, String key) =>
      wasmModule.wire__crate__api__multipart__start_multipart(
          port_, client, bucket, key);

  void wire__crate__api__multipart__upload_large_file_simple(
          NativePortType port_,
          int client,
          String bucket,
          String key,
          JSAny data,
          int? chunk_size) =>
      wasmModule.wire__crate__api__multipart__upload_large_file_simple(
          port_, client, bucket, key, data, chunk_size);

  void wire__crate__api__multipart__upload_part(
          NativePortType port_, int handle, int part_number, JSAny data) =>
      wasmModule.wire__crate__api__multipart__upload_part(
          port_, handle, part_number, data);

  void wire__crate__api__types__upload_progress_new(
          NativePortType port_,
          JSAny bytes_uploaded,
          JSAny total_bytes,
          int current_part,
          int total_parts) =>
      wasmModule.wire__crate__api__types__upload_progress_new(
          port_, bytes_uploaded, total_bytes, current_part, total_parts);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__multipart__abort_multipart(
      NativePortType port_, int handle);

  external void wire__crate__api__sharing__accept_share(
      NativePortType port_, int client, String token_json);

  external void wire__crate__api__client__bucket_exists(
      NativePortType port_, int client, String name);

  external void wire__crate__api__multipart__complete_multipart(
      NativePortType port_, int handle);

  external void wire__crate__api__client__copy_object(
      NativePortType port_,
      int client,
      String src_bucket,
      String src_key,
      String dst_bucket,
      String dst_key);

  external void wire__crate__api__client__create_bucket(
      NativePortType port_, int client, String name);

  external void wire__crate__api__client__create_client(
      NativePortType port_, JSAny config);

  external void wire__crate__api__client__create_encrypted_client(
      NativePortType port_, JSAny config, JSAny encryption);

  external void wire__crate__api__client__create_encrypted_client_with_pinning(
      NativePortType port_, JSAny config, JSAny encryption, JSAny pinning);

  external void wire__crate__api__rotation__create_rotation_manager(
      NativePortType port_, int client);

  external void wire__crate__api__sharing__create_share_token(
      NativePortType port_,
      int client,
      String storage_key,
      JSAny recipient_public_key,
      JSAny? expires_at);

  external void wire__crate__api__sharing__create_share_token_with_mode(
      NativePortType port_,
      int client,
      String storage_key,
      JSAny recipient_public_key,
      int mode,
      JSAny? expires_at);

  external void wire__crate__api__client__delete_bucket(
      NativePortType port_, int client, String name);

  external void wire__crate__api__encrypted__delete_by_storage_key(
      NativePortType port_, int client, String bucket, String storage_key);

  external void wire__crate__api__encrypted__delete_encrypted(
      NativePortType port_, int client, String bucket, String key);

  external void wire__crate__api__forest__delete_flat(
      NativePortType port_, int client, String bucket, String path);

  external void wire__crate__api__client__delete_object(
      NativePortType port_, int client, String bucket, String key);

  external void wire__crate__api__encrypted__enc_create_bucket(
      NativePortType port_, int client, String name);

  external void wire__crate__api__encrypted__enc_delete_bucket(
      NativePortType port_, int client, String name);

  external void wire__crate__api__encrypted__enc_list_buckets(
      NativePortType port_, int client);

  external void wire__crate__api__types__encryption_config_default(
      NativePortType port_);

  external void wire__crate__api__encrypted__export_secret_key(
      NativePortType port_, int client);

  external void wire__crate__api__forest__flush_forest(
      NativePortType port_, int client, String bucket);

  external void wire__crate__api__types__fula_config_default(
      NativePortType port_);

  external void wire__crate__api__error__fula_error_error_code(
      NativePortType port_, JSAny that);

  external void wire__crate__api__error__fula_error_is_access_denied(
      NativePortType port_, JSAny that);

  external void wire__crate__api__error__fula_error_is_encryption_error(
      NativePortType port_, JSAny that);

  external void wire__crate__api__error__fula_error_is_network_error(
      NativePortType port_, JSAny that);

  external void wire__crate__api__error__fula_error_is_not_found(
      NativePortType port_, JSAny that);

  external void wire__crate__api__chunked__get_chunked(
      NativePortType port_, int client, String bucket, String key);

  external void wire__crate__api__multipart__get_completed_parts(
      NativePortType port_, int handle);

  external void wire__crate__api__encrypted__get_decrypted(
      NativePortType port_, int client, String bucket, String key);

  external void wire__crate__api__encrypted__get_decrypted_by_storage_key(
      NativePortType port_, int client, String bucket, String storage_key);

  external void wire__crate__api__forest__get_flat(
      NativePortType port_, int client, String bucket, String path);

  external void wire__crate__api__forest__get_forest_subtree(
      NativePortType port_, int client, String bucket, String prefix);

  external void wire__crate__api__rotation__get_kek_version(
      NativePortType port_, int client, String bucket, String storage_key);

  external void wire__crate__api__client__get_object(
      NativePortType port_, int client, String bucket, String key);

  external void wire__crate__api__client__get_object_with_metadata(
      NativePortType port_, int client, String bucket, String key);

  external void wire__crate__api__encrypted__get_public_key(
      NativePortType port_, int client);

  external void wire__crate__api__chunked__get_range(NativePortType port_,
      int client, String bucket, String key, JSAny offset, JSAny length);

  external void wire__crate__api__sharing__get_share_permissions(
      NativePortType port_, int share);

  external void wire__crate__api__multipart__get_upload_id(
      NativePortType port_, int handle);

  external void wire__crate__api__encrypted__get_with_private_metadata(
      NativePortType port_, int client, String bucket, String storage_key);

  external void wire__crate__api__sharing__get_with_share(NativePortType port_,
      int client, String bucket, String storage_key, int share);

  external void wire__crate__api__sharing__get_with_token(NativePortType port_,
      int client, String bucket, String storage_key, String token_json);

  external void wire__crate__api__forest__has_pending_changes(
      NativePortType port_, int client, String bucket);

  external void wire__crate__api__encrypted__head_decrypted(
      NativePortType port_, int client, String bucket, String storage_key);

  external void wire__crate__api__client__head_object(
      NativePortType port_, int client, String bucket, String key);

  external void wire__crate__api__encrypted__is_flat_namespace(
      NativePortType port_, int client);

  external void wire__crate__api__sharing__is_share_expired(
      NativePortType port_, int share);

  external void wire__crate__api__client__list_buckets(
      NativePortType port_, int client);

  external void wire__crate__api__encrypted__list_decrypted(
      NativePortType port_, int client, String bucket, JSAny options);

  external void wire__crate__api__encrypted__list_directory(
      NativePortType port_, int client, String bucket, String? prefix);

  external void wire__crate__api__forest__list_from_forest(
      NativePortType port_, int client, String bucket);

  external void wire__crate__api__client__list_objects(
      NativePortType port_, int client, String bucket, JSAny options);

  external void wire__crate__api__types__list_options_default(
      NativePortType port_);

  external void wire__crate__api__forest__load_forest(
      NativePortType port_, int client, String bucket);

  external void wire__crate__api__types__obfuscation_mode_default(
      NativePortType port_);

  external void wire__crate__api__client__object_exists(
      NativePortType port_, int client, String bucket, String key);

  external void wire__crate__api__types__object_metadata_default(
      NativePortType port_);

  external void wire__crate__api__chunked__put_chunked(NativePortType port_,
      int client, String bucket, String key, JSAny data, int? chunk_size);

  external void wire__crate__api__encrypted__put_encrypted(
      NativePortType port_, int client, String bucket, String key, JSAny data);

  external void wire__crate__api__encrypted__put_encrypted_with_type(
      NativePortType port_,
      int client,
      String bucket,
      String key,
      JSAny data,
      String content_type);

  external void wire__crate__api__forest__put_flat(NativePortType port_,
      int client, String bucket, String path, JSAny data, String? content_type);

  external void wire__crate__api__forest__put_flat_deferred(
      NativePortType port_,
      int client,
      String bucket,
      String path,
      JSAny data,
      String? content_type);

  external void wire__crate__api__client__put_object(
      NativePortType port_, int client, String bucket, String key, JSAny data);

  external void wire__crate__api__client__put_object_with_metadata(
      NativePortType port_,
      int client,
      String bucket,
      String key,
      JSAny data,
      JSAny metadata);

  external void wire__crate__api__rotation__rewrap_object(NativePortType port_,
      int client, String bucket, String storage_key, int manager);

  external void wire__crate__api__rotation__rotate_bucket(
      NativePortType port_, int client, String bucket, int manager);

  external void wire__crate__api__types__rotation_report_is_success(
      NativePortType port_, JSAny that);

  external void wire__crate__api__types__rotation_report_success_rate(
      NativePortType port_, JSAny that);

  external void wire__crate__api__forest__save_forest(
      NativePortType port_, int client, String bucket);

  external void wire__crate__api__chunked__should_use_chunked(
      NativePortType port_, JSAny size);

  external void wire__crate__api__multipart__start_multipart(
      NativePortType port_, int client, String bucket, String key);

  external void wire__crate__api__multipart__upload_large_file_simple(
      NativePortType port_,
      int client,
      String bucket,
      String key,
      JSAny data,
      int? chunk_size);

  external void wire__crate__api__multipart__upload_part(
      NativePortType port_, int handle, int part_number, JSAny data);

  external void wire__crate__api__types__upload_progress_new(
      NativePortType port_,
      JSAny bytes_uploaded,
      JSAny total_bytes,
      int current_part,
      int total_parts);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAcceptedShareHandle(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEncryptedClientHandle(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFulaClientHandle(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultipartHandle(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotationManagerHandle(
          int ptr);
}
