// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Upload a large file using chunked encryption
///
/// The file is split into chunks, each encrypted separately.
/// This is more efficient for large files and enables partial downloads.
Future<PutResult> putChunked(
        {required EncryptedClientHandle client,
        required String bucket,
        required String key,
        required List<int> data,
        int? chunkSize}) =>
    RustLib.instance.api.crateApiChunkedPutChunked(
        client: client,
        bucket: bucket,
        key: key,
        data: data,
        chunkSize: chunkSize);

/// Download and decrypt a chunked file
///
/// Automatically handles reassembly of chunks.
Future<Uint8List> getChunked(
        {required EncryptedClientHandle client,
        required String bucket,
        required String key}) =>
    RustLib.instance.api
        .crateApiChunkedGetChunked(client: client, bucket: bucket, key: key);

/// Download a range of bytes from a file
///
/// For chunked files, only the necessary chunks are downloaded.
/// This is efficient for large files when you only need part of the content.
Future<Uint8List> getRange(
        {required EncryptedClientHandle client,
        required String bucket,
        required String key,
        required BigInt offset,
        required BigInt length}) =>
    RustLib.instance.api.crateApiChunkedGetRange(
        client: client,
        bucket: bucket,
        key: key,
        offset: offset,
        length: length);

/// Check if a file size warrants chunked upload
///
/// Returns true if the size is above the chunked threshold.
Future<bool> shouldUseChunked({required BigInt size}) =>
    RustLib.instance.api.crateApiChunkedShouldUseChunked(size: size);
