// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Upload an encrypted object
Future<PutResult> putEncrypted({
  required EncryptedClientHandle client,
  required String bucket,
  required String key,
  required List<int> data,
}) => RustLib.instance.api.crateApiEncryptedPutEncrypted(
  client: client,
  bucket: bucket,
  key: key,
  data: data,
);

/// Upload an encrypted object with specific content type
Future<PutResult> putEncryptedWithType({
  required EncryptedClientHandle client,
  required String bucket,
  required String key,
  required List<int> data,
  required String contentType,
}) => RustLib.instance.api.crateApiEncryptedPutEncryptedWithType(
  client: client,
  bucket: bucket,
  key: key,
  data: data,
  contentType: contentType,
);

/// Download and decrypt an object by original key
Future<Uint8List> getDecrypted({
  required EncryptedClientHandle client,
  required String bucket,
  required String key,
}) => RustLib.instance.api.crateApiEncryptedGetDecrypted(
  client: client,
  bucket: bucket,
  key: key,
);

/// Download and decrypt an object by storage key
Future<Uint8List> getDecryptedByStorageKey({
  required EncryptedClientHandle client,
  required String bucket,
  required String storageKey,
}) => RustLib.instance.api.crateApiEncryptedGetDecryptedByStorageKey(
  client: client,
  bucket: bucket,
  storageKey: storageKey,
);

/// F8: Buffered, root-hash-verified download by original key.
///
/// Holds the full plaintext in RAM and only returns after the BAO root-hash
/// check passes, closing the mid-stream truncation / chunk-reorder window
/// that the streaming variant accepts. Rejects files larger than
/// `FulaConfig::buffered_download_max_bytes` before any network I/O.
///
/// Prefer this over `get_decrypted` for disaster-recovery consumers that
/// must not observe any plaintext until the whole file has been verified.
Future<Uint8List> getDecryptedBuffered({
  required EncryptedClientHandle client,
  required String bucket,
  required String key,
}) => RustLib.instance.api.crateApiEncryptedGetDecryptedBuffered(
  client: client,
  bucket: bucket,
  key: key,
);

/// F8: Buffered, root-hash-verified download by storage key.
///
/// See `get_decrypted_buffered` for semantics.
Future<Uint8List> getDecryptedBufferedByStorageKey({
  required EncryptedClientHandle client,
  required String bucket,
  required String storageKey,
}) => RustLib.instance.api.crateApiEncryptedGetDecryptedBufferedByStorageKey(
  client: client,
  bucket: bucket,
  storageKey: storageKey,
);

/// Download and decrypt with full metadata
Future<DecryptedObjectInfo> getWithPrivateMetadata({
  required EncryptedClientHandle client,
  required String bucket,
  required String storageKey,
}) => RustLib.instance.api.crateApiEncryptedGetWithPrivateMetadata(
  client: client,
  bucket: bucket,
  storageKey: storageKey,
);

/// Delete an encrypted object by original key
Future<void> deleteEncrypted({
  required EncryptedClientHandle client,
  required String bucket,
  required String key,
}) => RustLib.instance.api.crateApiEncryptedDeleteEncrypted(
  client: client,
  bucket: bucket,
  key: key,
);

/// Delete an encrypted object by storage key
Future<void> deleteByStorageKey({
  required EncryptedClientHandle client,
  required String bucket,
  required String storageKey,
}) => RustLib.instance.api.crateApiEncryptedDeleteByStorageKey(
  client: client,
  bucket: bucket,
  storageKey: storageKey,
);

/// Get decrypted metadata without downloading content
Future<FileMetadata> headDecrypted({
  required EncryptedClientHandle client,
  required String bucket,
  required String storageKey,
}) => RustLib.instance.api.crateApiEncryptedHeadDecrypted(
  client: client,
  bucket: bucket,
  storageKey: storageKey,
);

/// List objects with decrypted metadata
Future<List<FileMetadata>> listDecrypted({
  required EncryptedClientHandle client,
  required String bucket,
  required ListOptions options,
}) => RustLib.instance.api.crateApiEncryptedListDecrypted(
  client: client,
  bucket: bucket,
  options: options,
);

/// List directory structure
Future<DirectoryListing> listDirectory({
  required EncryptedClientHandle client,
  required String bucket,
  String? prefix,
}) => RustLib.instance.api.crateApiEncryptedListDirectory(
  client: client,
  bucket: bucket,
  prefix: prefix,
);

/// Export the secret key for backup
Future<Uint8List> exportSecretKey({required EncryptedClientHandle client}) =>
    RustLib.instance.api.crateApiEncryptedExportSecretKey(client: client);

/// Get the public key for sharing
Future<Uint8List> getPublicKey({required EncryptedClientHandle client}) =>
    RustLib.instance.api.crateApiEncryptedGetPublicKey(client: client);

/// Derive X25519 public key from private key bytes
///
/// **IMPORTANT**: Use this function instead of Dart's X25519 public key derivation
/// to ensure compatibility between Flutter and Web/WASM clients.
///
/// This ensures that both FxFiles and Web UI derive the exact same public key
/// from the same private key bytes, avoiding cryptographic mismatches.
///
/// # Arguments
/// * `secret_key_bytes` - 32-byte X25519 private key (raw bytes, not clamped)
///
/// # Returns
/// * `Ok(Vec<u8>)` - 32-byte X25519 public key
/// * `Err` - If secret_key_bytes is not exactly 32 bytes
///
/// # Example
/// ```dart
/// // In Flutter/Dart, generate random 32 bytes:
/// final secretKeyBytes = Uint8List(32);
/// Random.secure().nextBytes(secretKeyBytes);
///
/// // Derive public key using Rust (ensures cross-platform compatibility):
/// final publicKeyBytes = await derivePublicKeyFromSecret(secretKeyBytes);
///
/// // Now use publicKeyBytes for createShareToken
/// // and secretKeyBytes in the share URL
/// ```
Future<Uint8List> derivePublicKeyFromSecret({
  required List<int> secretKeyBytes,
}) => RustLib.instance.api.crateApiEncryptedDerivePublicKeyFromSecret(
  secretKeyBytes: secretKeyBytes,
);

/// Derive a 32-byte key using Argon2id (memory-hard KDF)
///
/// **IMPORTANT**: Use this function to derive encryption keys from user credentials
/// instead of platform-specific PBKDF2 implementations.
///
/// This ensures both FxFiles (Flutter) and WebUI (WASM) derive the exact same key
/// from the same inputs, with brute-force resistance from Argon2id's memory-hardness.
///
/// Parameters:
/// - Memory: 64 MiB
/// - Iterations: 3
/// - Parallelism: 1 (for cross-platform consistency)
///
/// # Arguments
/// * `context` - A context string used as salt (e.g., "fula-files-v1")
/// * `input` - The input bytes (e.g., UTF-8 encoded "google:{userId}:{email}")
///
/// # Returns
/// * 32-byte derived key
///
/// # Example
/// ```dart
/// // Derive encryption key from Google credentials (same as WebUI):
/// final input = utf8.encode('google:${userId}:${email}');
/// final secretKey = await deriveKey(context: 'fula-files-v1', input: input);
///
/// // Use secretKey for createEncryptedClient
/// ```
Future<Uint8List> deriveKey({
  required String context,
  required List<int> input,
}) => RustLib.instance.api.crateApiEncryptedDeriveKey(
  context: context,
  input: input,
);

/// Derive a 32-byte sub-key from a high-entropy parent key using
/// BLAKE3's keyed-derivation mode (`blake3::Hasher::new_derive_key`).
///
/// Used by the E2E plan Phase 5 to derive `K_index` and `K_entry_seed`
/// from the user's already-derived `KEK_seed` (= `_encryptionKey` in
/// FxFiles, produced by Argon2id). BLAKE3-derive is the right primitive
/// here because:
/// 1. Input is already key-strength (32 bytes from Argon2id) â€” no need
///    for memory-hardness again.
/// 2. Output is byte-identical to the Rust side's
///    `derive_entry_signing_seed` / `derive_user_buckets_index_key`,
///    which use the same `blake3::Hasher::new_derive_key(context)`.
///
/// Distinct from [`derive_key`] (Argon2id, memory-hard, for stretching
/// a user-typed passphrase into a master key).
///
/// # Arguments
/// * `context` â€” domain-separation tag (e.g., `"fula:user-buckets-index:v1"`)
/// * `input`   â€” parent key bytes (e.g., the 32-byte `KEK_seed`)
///
/// # Returns
/// * 32-byte derived sub-key.
Future<Uint8List> blake3DeriveKey({
  required String context,
  required List<int> input,
}) => RustLib.instance.api.crateApiEncryptedBlake3DeriveKey(
  context: context,
  input: input,
);

/// Derive a 32-byte key using Argon2id with an EXPLICIT per-user salt.
///
/// This is the audit F-A1 / issue #14 Mode B variant. Compared to
/// [`derive_key`], which uses the `context` bytes as the salt, this
/// variant takes the salt as a separate parameter so callers can
/// supply a per-user random salt â€” closing the F-A1 finding (the
/// master key is no longer derivable from public identity attributes
/// alone).
///
/// Cross-platform parity: the underlying
/// `fula_crypto::hashing::derive_key_argon2id_with_salt` is pure Rust
/// and is reachable from both native (FxFiles) and WASM (WebUI) so the
/// derived key is byte-identical across platforms for the same
/// (context, input, salt) triple.
///
/// Mode A users continue to call [`derive_key`] (legacy behavior,
/// unchanged). Mode B users call this function with their per-user
/// random salt.
///
/// # Arguments
/// * `context` â€” domain-separation tag (e.g., `"fula-files-v1-google-pw"`)
/// * `input`   â€” UTF-8 bytes of the identity-plus-seed string
///               (e.g., `"google:<sub>:<email>:<seed>"`)
/// * `salt`    â€” per-user random salt; minimum 8 bytes, recommended 32
///
/// # Returns
/// * 32-byte derived key, or an error string if the salt is too short
Future<Uint8List> deriveKeyWithSalt({
  required String context,
  required List<int> input,
  required List<int> salt,
}) => RustLib.instance.api.crateApiEncryptedDeriveKeyWithSalt(
  context: context,
  input: input,
  salt: salt,
);

/// Compute the **Mode B** `effective_user_id` (OAuth + seed).
///
/// Returns a 16-byte identifier suitable as the JWT `sub` claim (after
/// hex encoding). The seed never leaves the device; whoever can
/// compute this id IS that user.
///
/// `provider` should be a canonical lowercase tag â€” `"google"` or
/// `"apple"`. `oauth_sub` is the IDP-issued opaque identifier. `seed`
/// is the user-entered passphrase / password; it is NFKC-normalized
/// internally before hashing.
///
/// See `fula_crypto::effective_user_id::compute_effective_user_id_mode_b`
/// for the full derivation specification.
Future<Uint8List> computeEffectiveUserIdModeB({
  required String provider,
  required String oauthSub,
  required String seed,
}) => RustLib.instance.api.crateApiEncryptedComputeEffectiveUserIdModeB(
  provider: provider,
  oauthSub: oauthSub,
  seed: seed,
);

/// Compute the **Mode C** (seed-only) `effective_user_id`.
///
/// Returns a 16-byte identifier suitable as the JWT `sub` claim (after
/// hex encoding). Two callers with the same seed produce the same
/// id â€” by design (the seed IS the identity). High-entropy seeds make
/// accidental collisions infeasible.
///
/// `seed` is NFKC-normalized internally before hashing.
Future<Uint8List> computeEffectiveUserIdModeC({required String seed}) => RustLib
    .instance
    .api
    .crateApiEncryptedComputeEffectiveUserIdModeC(seed: seed);

/// Derive a deterministic 32-byte Ed25519 signing-key seed from the
/// user's seed.
///
/// Use the returned bytes to construct an Ed25519 signing key (e.g.,
/// in Dart via the `cryptography` package or the `ed25519` package).
/// The corresponding public key is what the token issuer stores at
/// registration time; subsequent sign-ins use challenge-response
/// (issuer sends a nonce, client signs with this key, issuer verifies).
///
/// Domain-separated from the `effective_user_id` derivations so the
/// signing seed and the user-id are independent functions of the
/// user's input.
Future<Uint8List> deriveSigningSeed({required String seed}) =>
    RustLib.instance.api.crateApiEncryptedDeriveSigningSeed(seed: seed);

/// Check if client uses FlatNamespace mode
Future<bool> isFlatNamespace({required EncryptedClientHandle client}) =>
    RustLib.instance.api.crateApiEncryptedIsFlatNamespace(client: client);

/// List buckets (delegated to inner client)
Future<List<BucketInfo>> encListBuckets({
  required EncryptedClientHandle client,
}) => RustLib.instance.api.crateApiEncryptedEncListBuckets(client: client);

/// Create bucket (delegated to inner client)
Future<void> encCreateBucket({
  required EncryptedClientHandle client,
  required String name,
}) => RustLib.instance.api.crateApiEncryptedEncCreateBucket(
  client: client,
  name: name,
);

/// Delete bucket (delegated to inner client)
Future<void> encDeleteBucket({
  required EncryptedClientHandle client,
  required String name,
}) => RustLib.instance.api.crateApiEncryptedEncDeleteBucket(
  client: client,
  name: name,
);
