// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Upload an encrypted object
Future<PutResult> putEncrypted(
        {required EncryptedClientHandle client,
        required String bucket,
        required String key,
        required List<int> data}) =>
    RustLib.instance.api.crateApiEncryptedPutEncrypted(
        client: client, bucket: bucket, key: key, data: data);

/// Upload an encrypted object with specific content type
Future<PutResult> putEncryptedWithType(
        {required EncryptedClientHandle client,
        required String bucket,
        required String key,
        required List<int> data,
        required String contentType}) =>
    RustLib.instance.api.crateApiEncryptedPutEncryptedWithType(
        client: client,
        bucket: bucket,
        key: key,
        data: data,
        contentType: contentType);

/// Download and decrypt an object by original key
Future<Uint8List> getDecrypted(
        {required EncryptedClientHandle client,
        required String bucket,
        required String key}) =>
    RustLib.instance.api.crateApiEncryptedGetDecrypted(
        client: client, bucket: bucket, key: key);

/// Download and decrypt an object by storage key
Future<Uint8List> getDecryptedByStorageKey(
        {required EncryptedClientHandle client,
        required String bucket,
        required String storageKey}) =>
    RustLib.instance.api.crateApiEncryptedGetDecryptedByStorageKey(
        client: client, bucket: bucket, storageKey: storageKey);

/// Download and decrypt with full metadata
Future<DecryptedObjectInfo> getWithPrivateMetadata(
        {required EncryptedClientHandle client,
        required String bucket,
        required String storageKey}) =>
    RustLib.instance.api.crateApiEncryptedGetWithPrivateMetadata(
        client: client, bucket: bucket, storageKey: storageKey);

/// Delete an encrypted object by original key
Future<void> deleteEncrypted(
        {required EncryptedClientHandle client,
        required String bucket,
        required String key}) =>
    RustLib.instance.api.crateApiEncryptedDeleteEncrypted(
        client: client, bucket: bucket, key: key);

/// Delete an encrypted object by storage key
Future<void> deleteByStorageKey(
        {required EncryptedClientHandle client,
        required String bucket,
        required String storageKey}) =>
    RustLib.instance.api.crateApiEncryptedDeleteByStorageKey(
        client: client, bucket: bucket, storageKey: storageKey);

/// Get decrypted metadata without downloading content
Future<FileMetadata> headDecrypted(
        {required EncryptedClientHandle client,
        required String bucket,
        required String storageKey}) =>
    RustLib.instance.api.crateApiEncryptedHeadDecrypted(
        client: client, bucket: bucket, storageKey: storageKey);

/// List objects with decrypted metadata
Future<List<FileMetadata>> listDecrypted(
        {required EncryptedClientHandle client,
        required String bucket,
        required ListOptions options}) =>
    RustLib.instance.api.crateApiEncryptedListDecrypted(
        client: client, bucket: bucket, options: options);

/// List directory structure
Future<DirectoryListing> listDirectory(
        {required EncryptedClientHandle client,
        required String bucket,
        String? prefix}) =>
    RustLib.instance.api.crateApiEncryptedListDirectory(
        client: client, bucket: bucket, prefix: prefix);

/// Export the secret key for backup
Future<Uint8List> exportSecretKey({required EncryptedClientHandle client}) =>
    RustLib.instance.api.crateApiEncryptedExportSecretKey(client: client);

/// Get the public key for sharing
Future<Uint8List> getPublicKey({required EncryptedClientHandle client}) =>
    RustLib.instance.api.crateApiEncryptedGetPublicKey(client: client);

/// Check if client uses FlatNamespace mode
Future<bool> isFlatNamespace({required EncryptedClientHandle client}) =>
    RustLib.instance.api.crateApiEncryptedIsFlatNamespace(client: client);

/// List buckets (delegated to inner client)
Future<List<BucketInfo>> encListBuckets(
        {required EncryptedClientHandle client}) =>
    RustLib.instance.api.crateApiEncryptedEncListBuckets(client: client);

/// Create bucket (delegated to inner client)
Future<void> encCreateBucket(
        {required EncryptedClientHandle client, required String name}) =>
    RustLib.instance.api
        .crateApiEncryptedEncCreateBucket(client: client, name: name);

/// Delete bucket (delegated to inner client)
Future<void> encDeleteBucket(
        {required EncryptedClientHandle client, required String name}) =>
    RustLib.instance.api
        .crateApiEncryptedEncDeleteBucket(client: client, name: name);
