// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `progress_cb`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProgressState`, `StreamingPhase`, `StreamingUploadInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

/// Load the forest index from storage.
///
/// For v7 (sharded-HAMT) forests the underlying `load_forest` returns a
/// marker error `"forest is sharded; use sharded API methods"` so that
/// callers using the monolithic `PrivateForest` API know to switch. All
/// real I/O paths on this client (`get_flat`, `put_flat`, â€¦) go through
/// `ensure_forest_loaded` which already handles the sharded path
/// transparently, so from a Flutter caller's perspective that marker is
/// not an error â€” the forest *is* loaded, just in sharded form. Swallow
/// the marker here so apps don't have to special-case it.
Future<void> loadForest({
  required EncryptedClientHandle client,
  required String bucket,
}) => RustLib.instance.api.crateApiForestLoadForest(
  client: client,
  bucket: bucket,
);

/// Save the forest index to storage
///
/// This is an alias for flush_forest. It saves any pending changes
/// in the forest cache to storage.
Future<void> saveForest({
  required EncryptedClientHandle client,
  required String bucket,
}) => RustLib.instance.api.crateApiForestSaveForest(
  client: client,
  bucket: bucket,
);

/// Flush any pending forest changes to storage
Future<void> flushForest({
  required EncryptedClientHandle client,
  required String bucket,
}) => RustLib.instance.api.crateApiForestFlushForest(
  client: client,
  bucket: bucket,
);

/// Check if there are pending (unsaved) forest changes
Future<bool> hasPendingChanges({
  required EncryptedClientHandle client,
  required String bucket,
}) => RustLib.instance.api.crateApiForestHasPendingChanges(
  client: client,
  bucket: bucket,
);

/// Invalidate the cached forest for `bucket` (issue #36).
///
/// The encrypted client caches each bucket's forest for the client
/// lifetime, so a long-lived session never observes another device's
/// uploads — `list_from_forest` / `get_flat` keep resolving against the
/// session-stale index. Calling this drops the cached forest so the next
/// forest operation reloads it from storage and sees cross-device writes.
///
/// **Dirty-safe**: a forest with pending (unsaved) local changes is NOT
/// evicted — call [`flush_forest`] first to persist, then invalidate.
/// Use [`has_pending_changes`] to inspect. This mirrors the underlying
/// `EncryptedClient::invalidate_forest_cache` contract.
///
/// Typical app wiring: call on pull-to-refresh, tab-resume, reconnect,
/// or any cache-revalidation path, then re-run `list_from_forest`.
Future<void> invalidateForestCache({
  required EncryptedClientHandle client,
  required String bucket,
}) => RustLib.instance.api.crateApiForestInvalidateForestCache(
  client: client,
  bucket: bucket,
);

/// Invalidate every cached bucket forest on this client (issue #36).
///
/// Bulk variant of [`invalidate_forest_cache`]: all clean forests are
/// dropped; forests with pending (unsaved) changes are kept, matching
/// the per-bucket dirty-safe contract.
Future<void> invalidateAllForestCaches({
  required EncryptedClientHandle client,
}) => RustLib.instance.api.crateApiForestInvalidateAllForestCaches(
  client: client,
);

/// Upload a file with immediate forest save
///
/// This is the recommended method for most use cases.
/// The file path is preserved in the encrypted forest index.
Future<PutResult> putFlat({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
  required List<int> data,
  String? contentType,
}) => RustLib.instance.api.crateApiForestPutFlat(
  client: client,
  bucket: bucket,
  path: path,
  data: data,
  contentType: contentType,
);

/// Upload a file without immediate forest save (deferred)
///
/// Use this for batch uploads, then call `flush_forest` when done.
/// More efficient for uploading many files at once.
Future<PutResult> putFlatDeferred({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
  required List<int> data,
  String? contentType,
}) => RustLib.instance.api.crateApiForestPutFlatDeferred(
  client: client,
  bucket: bucket,
  path: path,
  data: data,
  contentType: contentType,
);

/// Download a file by its path
Future<Uint8List> getFlat({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
}) => RustLib.instance.api.crateApiForestGetFlat(
  client: client,
  bucket: bucket,
  path: path,
);

/// Delete a file by its path
Future<void> deleteFlat({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
}) => RustLib.instance.api.crateApiForestDeleteFlat(
  client: client,
  bucket: bucket,
  path: path,
);

/// List all files from the forest index (no network calls)
///
/// This reads from the local forest index, which is faster
/// than listing from the server.
Future<List<FileMetadata>> listFromForest({
  required EncryptedClientHandle client,
  required String bucket,
}) => RustLib.instance.api.crateApiForestListFromForest(
  client: client,
  bucket: bucket,
);

/// Upload a file from a local path with immediate forest save
///
/// Unlike `put_flat`, this reads the file on the Rust side, avoiding the need
/// to pass the entire file contents across the Flutter-Rust FFI boundary.
/// This is critical for large files (1GB+) where passing `Vec<u8>` through
/// FFI would cause out-of-memory errors.
Future<PutResult> putFlatFromPath({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
  required String filePath,
  String? contentType,
}) => RustLib.instance.api.crateApiForestPutFlatFromPath(
  client: client,
  bucket: bucket,
  path: path,
  filePath: filePath,
  contentType: contentType,
);

/// Upload a file from a local path without immediate forest save (deferred)
///
/// Same as `put_flat_from_path` but defers the forest save for batch efficiency.
Future<PutResult> putFlatFromPathDeferred({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
  required String filePath,
  String? contentType,
}) => RustLib.instance.api.crateApiForestPutFlatFromPathDeferred(
  client: client,
  bucket: bucket,
  path: path,
  filePath: filePath,
  contentType: contentType,
);

/// Upload a file from a local path with chunk-level resumable support.
///
/// Writes a manifest at `manifest_path` recording which chunks succeeded.
/// On clean completion the manifest is auto-deleted. On failure the
/// manifest stays on disk; call [`resume_flat_upload_from_path`] with the
/// SAME `manifest_path` AND the SAME `file_path` to pick up where this
/// attempt left off.
///
/// **Bytes contract.** The SDK's BAO root-hash check (F1 nonce-reuse
/// protection) on the resume path requires bit-identical `data` between
/// the original attempt and the resume. Metadata, permissions, mtime,
/// and the file's location on disk do NOT matter â€” only the bytes. If
/// the file changed between attempts, the resume fails fast with a
/// content-hash-mismatch error and the manifest stays on disk so the
/// caller can decide whether to give up or restart.
///
/// **Manifest path semantics.** Caller-owned local state, NOT bytes on
/// the storage backend. Recommended: place under the app's documents/
/// state directory, named by SyncTask ID or by hash of `(bucket, key)`.
/// Two concurrent calls against the SAME `manifest_path` are serialized
/// by the per-bucket write mutex (issue #16 + #17); the second caller
/// either re-finalizes the now-empty manifest cleanly or observes its
/// deletion and returns a typed error.
///
/// **WASM:** unsupported (no filesystem manifest available).
Future<PutResult> putFlatResumableFromPath({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
  required String filePath,
  required String manifestPath,
  String? contentType,
}) => RustLib.instance.api.crateApiForestPutFlatResumableFromPath(
  client: client,
  bucket: bucket,
  path: path,
  filePath: filePath,
  manifestPath: manifestPath,
  contentType: contentType,
);

/// Resume a previously-failed chunked upload from its manifest file.
///
/// Reads the manifest, re-encrypts and uploads only the chunks that
/// didn't complete on the previous attempt, finalizes the index object,
/// and deletes the manifest on success. See
/// [`put_flat_resumable_from_path`] for the bytes contract and manifest
/// semantics.
///
/// **WASM:** unsupported (no filesystem manifest available).
Future<PutResult> resumeFlatUploadFromPath({
  required EncryptedClientHandle client,
  required String manifestPath,
  required String filePath,
}) => RustLib.instance.api.crateApiForestResumeFlatUploadFromPath(
  client: client,
  manifestPath: manifestPath,
  filePath: filePath,
);

/// Create a fresh, untriggered cancellation handle.
Future<CancelHandle> createCancelHandle() =>
    RustLib.instance.api.crateApiForestCreateCancelHandle();

/// Trigger cancellation. Idempotent â€” second trigger is a no-op.
/// Any in-flight `_cancellable` upload using this handle (or a clone)
/// will short-circuit at its next chunk-PUT check.
Future<void> cancelHandleTrigger({required CancelHandle handle}) =>
    RustLib.instance.api.crateApiForestCancelHandleTrigger(handle: handle);

/// Check whether the handle has been triggered. Mostly useful for
/// tests and UI status checks; the upload functions themselves do
/// not need to be polled.
Future<bool> cancelHandleIsCancelled({required CancelHandle handle}) =>
    RustLib.instance.api.crateApiForestCancelHandleIsCancelled(handle: handle);

/// Cancellable variant of `put_flat_resumable_from_path`. Cancellation
/// semantics are documented on [`CancelHandle`].
Future<PutResult> putFlatResumableFromPathCancellable({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
  required String filePath,
  required String manifestPath,
  String? contentType,
  required CancelHandle cancel,
}) => RustLib.instance.api.crateApiForestPutFlatResumableFromPathCancellable(
  client: client,
  bucket: bucket,
  path: path,
  filePath: filePath,
  manifestPath: manifestPath,
  contentType: contentType,
  cancel: cancel,
);

/// Cancellable variant of `resume_flat_upload_from_path`.
Future<PutResult> resumeFlatUploadFromPathCancellable({
  required EncryptedClientHandle client,
  required String manifestPath,
  required String filePath,
  required CancelHandle cancel,
}) => RustLib.instance.api.crateApiForestResumeFlatUploadFromPathCancellable(
  client: client,
  manifestPath: manifestPath,
  filePath: filePath,
  cancel: cancel,
);

/// Discard a resumable upload's local state and best-effort delete its
/// already-uploaded chunks on the storage backend (issue #20).
///
/// Use when the caller decides to give up on a cancelled or failed
/// upload rather than resume. **Idempotent** â€” calling on a manifest
/// that doesn't exist (e.g. already aborted, or SDK auto-deleted it on
/// a prior clean completion) succeeds as a no-op. This matches Phase C
/// "discard cancelled upload" UX semantics: pressing the button always
/// leaves the system in a clean state, regardless of prior state.
///
/// **NOT a graceful stop.** This is POST-cancel cleanup. For mid-flight
/// abort, see [`cancel_handle_trigger`] on a [`CancelHandle`] passed to
/// the `_cancellable` variants (issue #18).
///
/// **Lock scope.** `client.inner.read().await` â€” same as the resumable
/// bridge functions. The underlying `abort_upload` doesn't touch the
/// encrypted forest (only the raw storage backend for chunk deletes
/// plus the local manifest file), so B1's per-bucket write mutex is
/// not needed here.
Future<void> abortResumableUpload({
  required EncryptedClientHandle client,
  required String manifestPath,
}) => RustLib.instance.api.crateApiForestAbortResumableUpload(
  client: client,
  manifestPath: manifestPath,
);

/// Get the size of a file without reading it into memory
Future<BigInt> getFileSize({required String filePath}) =>
    RustLib.instance.api.crateApiForestGetFileSize(filePath: filePath);

/// Create a fresh progress handle (0 / 0). Pass it to a `_with_progress`
/// upload function and read it via [`poll_progress`].
Future<ProgressHandle> createProgressHandle() =>
    RustLib.instance.api.crateApiForestCreateProgressHandle();

/// Read the latest progress for an in-flight (or finished) upload. Safe to
/// call any time, from any thread; returns 0% before the first chunk lands.
///
/// **100% caveat:** cumulative bytes reach `total` when the LAST content
/// chunk's PUT returns — BEFORE the index PUT + forest-flush tail. UIs that
/// show a determinate bar should cap at <100% until their own completion
/// signal (the upload future resolving), mirroring the mobile clamp.
Future<UploadProgress> pollProgress({required ProgressHandle handle}) =>
    RustLib.instance.api.crateApiForestPollProgress(handle: handle);

/// [`put_flat`] with live progress (web + native). Drive a percentage by
/// polling [`poll_progress`] on the passed [`ProgressHandle`] while this
/// future runs.
Future<PutResult> putFlatWithProgress({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
  required List<int> data,
  String? contentType,
  required ProgressHandle progress,
}) => RustLib.instance.api.crateApiForestPutFlatWithProgress(
  client: client,
  bucket: bucket,
  path: path,
  data: data,
  contentType: contentType,
  progress: progress,
);

/// [`put_flat_with_progress`] with cooperative cancellation (web + native).
/// Non-resumable: triggering `cancel` aborts the in-flight upload (chunks
/// already in flight finish, later chunks short-circuit, uploaded chunks are
/// cleaned up) and the call returns a `Cancelled` error. A cancelled upload
/// restarts from scratch — wasm resumable support lands separately. This is
/// web's cancel path (the native resumable+manifest cancel is the
/// `*_from_path` family, which is native-only).
Future<PutResult> putFlatWithProgressCancellable({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
  required List<int> data,
  String? contentType,
  required ProgressHandle progress,
  required CancelHandle cancel,
}) => RustLib.instance.api.crateApiForestPutFlatWithProgressCancellable(
  client: client,
  bucket: bucket,
  path: path,
  data: data,
  contentType: contentType,
  progress: progress,
  cancel: cancel,
);

/// Begin a streaming upload: run the prelude (DEK, storage_key, wrapped DEK,
/// KEK version) and create the plan-only encoder. Drive the returned handle via
/// `streaming_upload_plan_chunk` (×N, in order) → `streaming_upload_finalize_plan`
/// → `streaming_upload_chunk` (×N) → `streaming_upload_finish`.
Future<StreamingUploadHandle> streamingUploadBegin({
  required EncryptedClientHandle client,
  required String bucket,
  required String key,
  String? contentType,
}) => RustLib.instance.api.crateApiForestStreamingUploadBegin(
  client: client,
  bucket: bucket,
  key: key,
  contentType: contentType,
);

/// Pass 1 — feed one plaintext slice (pushed from Dart) into the plan-only
/// encoder. MUST be called sequentially in file order (BAO is order-sensitive).
Future<void> streamingUploadPlanChunk({
  required StreamingUploadHandle handle,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiForestStreamingUploadPlanChunk(
  handle: handle,
  bytes: bytes,
);

/// End of pass 1 — finalize the plan, commit per-file metadata, and return the
/// chunk count + chunk size so Dart can slice pass 2.
Future<StreamingPlanInfo> streamingUploadFinalizePlan({
  required StreamingUploadHandle handle,
}) => RustLib.instance.api.crateApiForestStreamingUploadFinalizePlan(
  handle: handle,
);

/// Pass 2 — encrypt + upload one chunk (pushed from Dart) using its committed
/// nonce. Safe to call concurrently for distinct indices (Dart bounds the
/// concurrency) and idempotent, so safe to retry.
Future<void> streamingUploadChunk({
  required StreamingUploadHandle handle,
  required int chunkIndex,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiForestStreamingUploadChunk(
  handle: handle,
  chunkIndex: chunkIndex,
  bytes: bytes,
);

/// Finalize ("commit") — write the index object, register the file in the
/// encrypted forest, and flush. After this the file is listable; before it the
/// uploaded chunks are unreferenced.
Future<PutResult> streamingUploadFinish({
  required StreamingUploadHandle handle,
}) => RustLib.instance.api.crateApiForestStreamingUploadFinish(handle: handle);

/// [`put_flat_resumable_from_path_cancellable`] with live progress (native).
Future<PutResult> putFlatResumableFromPathWithProgress({
  required EncryptedClientHandle client,
  required String bucket,
  required String path,
  required String filePath,
  required String manifestPath,
  String? contentType,
  required CancelHandle cancel,
  required ProgressHandle progress,
}) => RustLib.instance.api.crateApiForestPutFlatResumableFromPathWithProgress(
  client: client,
  bucket: bucket,
  path: path,
  filePath: filePath,
  manifestPath: manifestPath,
  contentType: contentType,
  cancel: cancel,
  progress: progress,
);

/// [`resume_flat_upload_from_path_cancellable`] with live progress (native).
/// Progress continues from the chunks the interrupted attempt already
/// uploaded (the SDK seeds the counter), so the bar resumes mid-way.
Future<PutResult> resumeFlatUploadFromPathWithProgress({
  required EncryptedClientHandle client,
  required String manifestPath,
  required String filePath,
  required CancelHandle cancel,
  required ProgressHandle progress,
}) => RustLib.instance.api.crateApiForestResumeFlatUploadFromPathWithProgress(
  client: client,
  manifestPath: manifestPath,
  filePath: filePath,
  cancel: cancel,
  progress: progress,
);

/// Extract a subtree from the forest for sharing
///
/// This creates a serialized subtree that can be shared with others.
/// The subtree includes all files under the given prefix.
Future<ForestSubtree> getForestSubtree({
  required EncryptedClientHandle client,
  required String bucket,
  required String prefix,
}) => RustLib.instance.api.crateApiForestGetForestSubtree(
  client: client,
  bucket: bucket,
  prefix: prefix,
);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CancelHandle>>
abstract class CancelHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProgressHandle>>
abstract class ProgressHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamingUploadHandle>>
abstract class StreamingUploadHandle implements RustOpaqueInterface {}

/// Returned by `streaming_upload_finalize_plan` so Dart knows how to slice
/// pass 2 (chunk `i` = file bytes `[i*chunk_size .. min((i+1)*chunk_size, len)]`).
class StreamingPlanInfo {
  final int numChunks;
  final int chunkSize;

  const StreamingPlanInfo({required this.numChunks, required this.chunkSize});

  @override
  int get hashCode => numChunks.hashCode ^ chunkSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamingPlanInfo &&
          runtimeType == other.runtimeType &&
          numChunks == other.numChunks &&
          chunkSize == other.chunkSize;
}
