// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Monotonic count of WAL append failures since process start.
///
/// Process-wide (not per-client). Not reset. Returns 0 on WASM where the
/// WAL module does not compile — a uniform shape across platforms simplifies
/// shared Dart code that monitors both mobile and web.
Future<BigInt> walAppendFailureCount() =>
    RustLib.instance.api.crateApiMetricsWalAppendFailureCount();
