// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Monotonic count of WAL append failures since process start.
///
/// Process-wide (not per-client). Not reset. Returns 0 on WASM where the
/// WAL module does not compile â€” a uniform shape across platforms simplifies
/// shared Dart code that monitors both mobile and web.
Future<BigInt> walAppendFailureCount() =>
    RustLib.instance.api.crateApiMetricsWalAppendFailureCount();

/// Monotonic count of flush-forest retry backoff sleeps observed since
/// process start (M-2).
///
/// Incremented each time the `flush_forest` retry loop sleeps on a 412
/// concurrent-modification race before re-attempting. Process-wide.
/// Returns 0 on WASM where `flush_forest` does a single attempt with no
/// retry/backoff.
Future<BigInt> flushBackoffCount() =>
    RustLib.instance.api.crateApiMetricsFlushBackoffCount();

/// Monotonic count of WAL groups discarded on load due to partial-group
/// truncation (M-4).
///
/// A transactional multi-entry op written via the internal `append_group`
/// path is applied all-or-none on replay: if any member is missing at load
/// time (power-loss between writes and the trailing fsync, MAC corruption,
/// index collision), every surviving member is dropped and this counter
/// increments once per discarded group. Returns 0 on WASM where the WAL is
/// compiled out.
Future<BigInt> walTruncatedGroupsCount() =>
    RustLib.instance.api.crateApiMetricsWalTruncatedGroupsCount();
