// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Start a new multipart upload
///
/// Returns a handle that can be used to upload parts. Uses the default
/// concurrency cap (`DEFAULT_MAX_CONCURRENT_PARTS`) for `upload_part` calls.
Future<MultipartHandle> startMultipart({
  required FulaClientHandle client,
  required String bucket,
  required String key,
}) => RustLib.instance.api.crateApiMultipartStartMultipart(
  client: client,
  bucket: bucket,
  key: key,
);

/// Start a new multipart upload with an explicit concurrency cap.
///
/// `max_concurrency` bounds how many `upload_part` calls can be in flight on
/// this handle at once. Values of 0 are coerced to 1 (fully serial).
Future<MultipartHandle> startMultipartWithConcurrency({
  required FulaClientHandle client,
  required String bucket,
  required String key,
  required int maxConcurrency,
}) => RustLib.instance.api.crateApiMultipartStartMultipartWithConcurrency(
  client: client,
  bucket: bucket,
  key: key,
  maxConcurrency: maxConcurrency,
);

/// Upload a part
///
/// Part numbers must be between 1 and 10000.
/// Parts can be uploaded in any order, and concurrent calls on the same
/// handle run their HTTP I/O in parallel up to the handle's concurrency cap.
Future<void> uploadPart({
  required MultipartHandle handle,
  required int partNumber,
  required List<int> data,
}) => RustLib.instance.api.crateApiMultipartUploadPart(
  handle: handle,
  partNumber: partNumber,
  data: data,
);

/// Complete the multipart upload
///
/// Assembles all uploaded parts into the final object.
/// Returns the ETag of the completed object.
Future<String> completeMultipart({required MultipartHandle handle}) =>
    RustLib.instance.api.crateApiMultipartCompleteMultipart(handle: handle);

/// Abort the multipart upload
///
/// Cancels the upload and removes any uploaded parts.
Future<void> abortMultipart({required MultipartHandle handle}) =>
    RustLib.instance.api.crateApiMultipartAbortMultipart(handle: handle);

/// Detach the multipart upload without aborting.
///
/// Suppresses the drop-time auto-abort so uploaded parts survive the
/// handle being GC'd. Use this when pausing a resumable upload — e.g.,
/// the user backgrounds the app mid-upload and you plan to resume later
/// with the same upload_id. Without detach, dropping the handle issues
/// a best-effort AbortMultipartUpload. (R4.)
Future<void> detachMultipart({required MultipartHandle handle}) =>
    RustLib.instance.api.crateApiMultipartDetachMultipart(handle: handle);

/// Get the upload ID
Future<String> getUploadId({required MultipartHandle handle}) =>
    RustLib.instance.api.crateApiMultipartGetUploadId(handle: handle);

/// Get the number of completed parts
Future<int> getCompletedParts({required MultipartHandle handle}) =>
    RustLib.instance.api.crateApiMultipartGetCompletedParts(handle: handle);

/// Upload a large file with automatic chunking
///
/// This is a convenience function that handles the entire multipart
/// upload process automatically, including progress reporting.
///
/// Note: For flutter_rust_bridge, progress streaming requires StreamSink.
/// This function provides a simpler interface without progress callbacks.
Future<String> uploadLargeFileSimple({
  required FulaClientHandle client,
  required String bucket,
  required String key,
  required List<int> data,
  int? chunkSize,
}) => RustLib.instance.api.crateApiMultipartUploadLargeFileSimple(
  client: client,
  bucket: bucket,
  key: key,
  data: data,
  chunkSize: chunkSize,
);
