// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Start a new multipart upload
///
/// Returns a handle that can be used to upload parts.
Future<MultipartHandle> startMultipart(
        {required FulaClientHandle client,
        required String bucket,
        required String key}) =>
    RustLib.instance.api.crateApiMultipartStartMultipart(
        client: client, bucket: bucket, key: key);

/// Upload a part
///
/// Part numbers must be between 1 and 10000.
/// Parts can be uploaded in any order.
Future<void> uploadPart(
        {required MultipartHandle handle,
        required int partNumber,
        required List<int> data}) =>
    RustLib.instance.api.crateApiMultipartUploadPart(
        handle: handle, partNumber: partNumber, data: data);

/// Complete the multipart upload
///
/// Assembles all uploaded parts into the final object.
/// Returns the ETag of the completed object.
Future<String> completeMultipart({required MultipartHandle handle}) =>
    RustLib.instance.api.crateApiMultipartCompleteMultipart(handle: handle);

/// Abort the multipart upload
///
/// Cancels the upload and removes any uploaded parts.
Future<void> abortMultipart({required MultipartHandle handle}) =>
    RustLib.instance.api.crateApiMultipartAbortMultipart(handle: handle);

/// Get the upload ID
Future<String> getUploadId({required MultipartHandle handle}) =>
    RustLib.instance.api.crateApiMultipartGetUploadId(handle: handle);

/// Get the number of completed parts
Future<int> getCompletedParts({required MultipartHandle handle}) =>
    RustLib.instance.api.crateApiMultipartGetCompletedParts(handle: handle);

/// Upload a large file with automatic chunking
///
/// This is a convenience function that handles the entire multipart
/// upload process automatically, including progress reporting.
///
/// Note: For flutter_rust_bridge, progress streaming requires StreamSink.
/// This function provides a simpler interface without progress callbacks.
Future<String> uploadLargeFileSimple(
        {required FulaClientHandle client,
        required String bucket,
        required String key,
        required List<int> data,
        int? chunkSize}) =>
    RustLib.instance.api.crateApiMultipartUploadLargeFileSimple(
        client: client,
        bucket: bucket,
        key: key,
        data: data,
        chunkSize: chunkSize);
