// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Create a share token for a file
///
/// This requires the recipient's public key. The token allows the recipient
/// to decrypt the specified file.
///
/// # Arguments
/// * `client` - The encrypted client handle
/// * `bucket` - The bucket containing the file
/// * `storage_key` - The storage key of the file to share
/// * `recipient_public_key` - The recipient's public key (32 bytes)
/// * `expires_at` - Optional expiration timestamp (Unix epoch seconds)
///
/// Returns a JSON-serialized share token that can be sent to the recipient.
Future<String> createShareToken({
  required EncryptedClientHandle client,
  required String bucket,
  required String storageKey,
  required List<int> recipientPublicKey,
  PlatformInt64? expiresAt,
}) => RustLib.instance.api.crateApiSharingCreateShareToken(
  client: client,
  bucket: bucket,
  storageKey: storageKey,
  recipientPublicKey: recipientPublicKey,
  expiresAt: expiresAt,
);

/// Create a share token with a specific mode
///
/// # Arguments
/// * `client` - The encrypted client handle
/// * `bucket` - The bucket containing the file
/// * `storage_key` - The storage key of the file to share
/// * `recipient_public_key` - The recipient's public key (32 bytes)
/// * `mode` - Share mode (Temporal or Snapshot)
/// * `expires_at` - Optional expiration timestamp (Unix epoch seconds)
///
/// Note: Snapshot mode requires additional binding data. This function defaults
/// to temporal mode for Snapshot shares since we don't have content hash info.
Future<String> createShareTokenWithMode({
  required EncryptedClientHandle client,
  required String bucket,
  required String storageKey,
  required List<int> recipientPublicKey,
  required ShareMode mode,
  PlatformInt64? expiresAt,
}) => RustLib.instance.api.crateApiSharingCreateShareTokenWithMode(
  client: client,
  bucket: bucket,
  storageKey: storageKey,
  recipientPublicKey: recipientPublicKey,
  mode: mode,
  expiresAt: expiresAt,
);

/// Wrap an ARBITRARY 32-byte secret for a recipient X25519 public key,
/// producing a serialized v5 ShareToken (JSON).
///
/// Unlike [`create_share_token`], this needs NO client and NO previously-stored
/// file: it wraps the raw 32 bytes you pass in. It is the producer side of the
/// secure "Method 2" AI-pairing — FxFiles' fail-closed `CollabLinkSecretWrapper`
/// calls this to wrap a collaboration link secret for an AI/MCP recipient's
/// public key. The recipient (the local MCP's
/// `McpIdentity::accept_link_secret`, i.e. `fula_crypto` `ShareRecipient`)
/// opens the token to recover the EXACT secret bytes.
///
/// The sender/owner keypair is generated EPHEMERALLY inside `fula-crypto`: the
/// v5 token AAD binds the RECIPIENT public key, not the sender, so the caller
/// needs no stable identity of its own.
///
/// # Arguments
/// * `secret` - the 32 raw secret bytes to wrap.
/// * `recipient_public_key` - the recipient's 32-byte X25519 public key.
/// * `path_scope` - optional scope string bound into the token (defaults to `"/"`).
/// * `expires_in_seconds` - optional expiry as seconds-from-now (`None` = never).
///
/// Returns the JSON-serialized ShareToken. Fails closed (returns `Err`) if
/// `secret` or `recipient_public_key` is not exactly 32 bytes.
Future<String> wrapSecretForRecipient({
  required List<int> secret,
  required List<int> recipientPublicKey,
  String? pathScope,
  PlatformInt64? expiresInSeconds,
}) => RustLib.instance.api.crateApiSharingWrapSecretForRecipient(
  secret: secret,
  recipientPublicKey: recipientPublicKey,
  pathScope: pathScope,
  expiresInSeconds: expiresInSeconds,
);

/// Accept a share token received from another user
Future<AcceptedShareHandle> acceptShare({
  required EncryptedClientHandle client,
  required String tokenJson,
}) => RustLib.instance.api.crateApiSharingAcceptShare(
  client: client,
  tokenJson: tokenJson,
);

/// Download a file using an accepted share
Future<Uint8List> getWithShare({
  required EncryptedClientHandle client,
  required String bucket,
  required String storageKey,
  required String originalKey,
  required AcceptedShareHandle share,
}) => RustLib.instance.api.crateApiSharingGetWithShare(
  client: client,
  bucket: bucket,
  storageKey: storageKey,
  originalKey: originalKey,
  share: share,
);

/// Download a file directly with a token (accept + download in one step)
Future<Uint8List> getWithToken({
  required EncryptedClientHandle client,
  required String bucket,
  required String storageKey,
  required String originalKey,
  required String tokenJson,
}) => RustLib.instance.api.crateApiSharingGetWithToken(
  client: client,
  bucket: bucket,
  storageKey: storageKey,
  originalKey: originalKey,
  tokenJson: tokenJson,
);

/// Get permissions granted by an accepted share
Future<SharePermissions> getSharePermissions({
  required AcceptedShareHandle share,
}) => RustLib.instance.api.crateApiSharingGetSharePermissions(share: share);

/// Check if an accepted share has expired
Future<bool> isShareExpired({required AcceptedShareHandle share}) =>
    RustLib.instance.api.crateApiSharingIsShareExpired(share: share);
