// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Create a share token for a file
///
/// This requires the recipient's public key. The token allows the recipient
/// to decrypt the specified file.
///
/// # Arguments
/// * `client` - The encrypted client handle
/// * `storage_key` - The storage key of the file to share
/// * `recipient_public_key` - The recipient's public key (32 bytes)
/// * `expires_at` - Optional expiration timestamp (Unix epoch seconds)
///
/// Returns a JSON-serialized share token that can be sent to the recipient.
Future<String> createShareToken(
        {required EncryptedClientHandle client,
        required String storageKey,
        required List<int> recipientPublicKey,
        PlatformInt64? expiresAt}) =>
    RustLib.instance.api.crateApiSharingCreateShareToken(
        client: client,
        storageKey: storageKey,
        recipientPublicKey: recipientPublicKey,
        expiresAt: expiresAt);

/// Create a share token with a specific mode
///
/// # Arguments
/// * `client` - The encrypted client handle
/// * `storage_key` - The storage key of the file to share
/// * `recipient_public_key` - The recipient's public key (32 bytes)
/// * `mode` - Share mode (Temporal or Snapshot)
/// * `expires_at` - Optional expiration timestamp (Unix epoch seconds)
///
/// Note: Snapshot mode requires additional binding data. This function defaults
/// to temporal mode for Snapshot shares since we don't have content hash info.
Future<String> createShareTokenWithMode(
        {required EncryptedClientHandle client,
        required String storageKey,
        required List<int> recipientPublicKey,
        required ShareMode mode,
        PlatformInt64? expiresAt}) =>
    RustLib.instance.api.crateApiSharingCreateShareTokenWithMode(
        client: client,
        storageKey: storageKey,
        recipientPublicKey: recipientPublicKey,
        mode: mode,
        expiresAt: expiresAt);

/// Accept a share token received from another user
Future<AcceptedShareHandle> acceptShare(
        {required EncryptedClientHandle client, required String tokenJson}) =>
    RustLib.instance.api
        .crateApiSharingAcceptShare(client: client, tokenJson: tokenJson);

/// Download a file using an accepted share
Future<Uint8List> getWithShare(
        {required EncryptedClientHandle client,
        required String bucket,
        required String storageKey,
        required AcceptedShareHandle share}) =>
    RustLib.instance.api.crateApiSharingGetWithShare(
        client: client, bucket: bucket, storageKey: storageKey, share: share);

/// Download a file directly with a token (accept + download in one step)
Future<Uint8List> getWithToken(
        {required EncryptedClientHandle client,
        required String bucket,
        required String storageKey,
        required String tokenJson}) =>
    RustLib.instance.api.crateApiSharingGetWithToken(
        client: client,
        bucket: bucket,
        storageKey: storageKey,
        tokenJson: tokenJson);

/// Get permissions granted by an accepted share
Future<SharePermissions> getSharePermissions(
        {required AcceptedShareHandle share}) =>
    RustLib.instance.api.crateApiSharingGetSharePermissions(share: share);

/// Check if an accepted share has expired
Future<bool> isShareExpired({required AcceptedShareHandle share}) =>
    RustLib.instance.api.crateApiSharingIsShareExpired(share: share);
