// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AcceptedShareHandle>>
abstract class AcceptedShareHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EncryptedClientHandle>>
abstract class EncryptedClientHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FulaClientHandle>>
abstract class FulaClientHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MultipartHandle>>
abstract class MultipartHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RotationManagerHandle>>
abstract class RotationManagerHandle implements RustOpaqueInterface {}

/// Information about a bucket
class BucketInfo {
  /// Bucket name
  final String name;

  /// Creation timestamp (Unix epoch seconds)
  final PlatformInt64 createdAt;

  const BucketInfo({required this.name, required this.createdAt});

  @override
  int get hashCode => name.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BucketInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          createdAt == other.createdAt;
}

/// Result of a copy operation
class CopyResult {
  /// ETag of the copied object
  final String etag;

  /// Last modified timestamp (Unix epoch seconds)
  final PlatformInt64 lastModified;

  const CopyResult({required this.etag, required this.lastModified});

  @override
  int get hashCode => etag.hashCode ^ lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CopyResult &&
          runtimeType == other.runtimeType &&
          etag == other.etag &&
          lastModified == other.lastModified;
}

/// Decrypted object with all metadata
class DecryptedObjectInfo {
  /// Decrypted data
  final Uint8List data;

  /// Original key/path
  final String originalKey;

  /// Original size
  final BigInt size;

  /// Content type
  final String? contentType;

  /// User metadata
  final List<MetadataEntry> metadata;

  const DecryptedObjectInfo({
    required this.data,
    required this.originalKey,
    required this.size,
    this.contentType,
    required this.metadata,
  });

  @override
  int get hashCode =>
      data.hashCode ^
      originalKey.hashCode ^
      size.hashCode ^
      contentType.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptedObjectInfo &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          originalKey == other.originalKey &&
          size == other.size &&
          contentType == other.contentType &&
          metadata == other.metadata;
}

/// A directory entry (file or subdirectory)
class DirectoryEntry {
  /// Name of entry
  final String name;

  /// Whether this is a directory
  final bool isDirectory;

  /// Files in this directory (if is_directory)
  final List<FileMetadata> files;

  const DirectoryEntry({
    required this.name,
    required this.isDirectory,
    required this.files,
  });

  @override
  int get hashCode => name.hashCode ^ isDirectory.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirectoryEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDirectory == other.isDirectory &&
          files == other.files;
}

/// Directory listing result
class DirectoryListing {
  /// Bucket name
  final String bucket;

  /// Prefix used for listing
  final String? prefix;

  /// Directory entries
  final List<DirectoryEntry> entries;

  const DirectoryListing({
    required this.bucket,
    this.prefix,
    required this.entries,
  });

  @override
  int get hashCode => bucket.hashCode ^ prefix.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirectoryListing &&
          runtimeType == other.runtimeType &&
          bucket == other.bucket &&
          prefix == other.prefix &&
          entries == other.entries;
}

/// Configuration for client-side encryption
class EncryptionConfig {
  /// Secret key bytes (32 bytes). If None, a new key is generated.
  final Uint8List? secretKey;

  /// Enable metadata privacy (obfuscates file names)
  final bool enableMetadataPrivacy;

  /// Obfuscation mode for file names
  final ObfuscationMode obfuscationMode;

  const EncryptionConfig({
    this.secretKey,
    required this.enableMetadataPrivacy,
    required this.obfuscationMode,
  });

  static Future<EncryptionConfig> default_() =>
      RustLib.instance.api.crateApiTypesEncryptionConfigDefault();

  @override
  int get hashCode =>
      secretKey.hashCode ^
      enableMetadataPrivacy.hashCode ^
      obfuscationMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptionConfig &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          enableMetadataPrivacy == other.enableMetadataPrivacy &&
          obfuscationMode == other.obfuscationMode;
}

/// Metadata for a decrypted file
class FileMetadata {
  /// Storage key (obfuscated name used in storage)
  final String storageKey;

  /// Original key (actual file path/name)
  final String originalKey;

  /// Original file size in bytes
  final BigInt size;

  /// Content type
  final String? contentType;

  /// Creation timestamp (Unix epoch seconds)
  final PlatformInt64? createdAt;

  /// Modification timestamp (Unix epoch seconds)
  final PlatformInt64? modifiedAt;

  /// Whether the file is encrypted
  final bool isEncrypted;

  const FileMetadata({
    required this.storageKey,
    required this.originalKey,
    required this.size,
    this.contentType,
    this.createdAt,
    this.modifiedAt,
    required this.isEncrypted,
  });

  @override
  int get hashCode =>
      storageKey.hashCode ^
      originalKey.hashCode ^
      size.hashCode ^
      contentType.hashCode ^
      createdAt.hashCode ^
      modifiedAt.hashCode ^
      isEncrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileMetadata &&
          runtimeType == other.runtimeType &&
          storageKey == other.storageKey &&
          originalKey == other.originalKey &&
          size == other.size &&
          contentType == other.contentType &&
          createdAt == other.createdAt &&
          modifiedAt == other.modifiedAt &&
          isEncrypted == other.isEncrypted;
}

/// Serialized forest subtree (for sharing)
class ForestSubtree {
  /// Serialized subtree data
  final Uint8List serialized;

  const ForestSubtree({required this.serialized});

  @override
  int get hashCode => serialized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForestSubtree &&
          runtimeType == other.runtimeType &&
          serialized == other.serialized;
}

/// Configuration for creating a Fula client
class FulaConfig {
  /// Gateway endpoint URL (e.g., "http://localhost:9000")
  final String endpoint;

  /// JWT access token for authentication
  final String? accessToken;

  /// Request timeout in seconds (default: 30)
  final BigInt timeoutSeconds;

  /// Maximum retry attempts (default: 3)
  final int maxRetries;

  /// F10: per-chunk download timeout in seconds.
  ///
  /// Applied to every individual chunk fetched by the windowed chunked-download
  /// engine. Guards against a slow server trickling bytes below the global
  /// dead-connection threshold. Only active on native targets; wasm inherits
  /// the browser fetch default. Default: 300 (5 minutes).
  final BigInt perChunkDownloadTimeoutSeconds;

  /// F8: maximum plaintext size a buffered download will accept.
  ///
  /// Applied *before* any network I/O by the buffered download path. If the
  /// chunked metadata declares a `total_size` larger than this ceiling, the
  /// buffered path returns an error instead of allocating the buffer.
  /// Default: 256 MiB.
  final BigInt bufferedDownloadMaxBytes;

  const FulaConfig({
    required this.endpoint,
    this.accessToken,
    required this.timeoutSeconds,
    required this.maxRetries,
    required this.perChunkDownloadTimeoutSeconds,
    required this.bufferedDownloadMaxBytes,
  });

  static Future<FulaConfig> default_() =>
      RustLib.instance.api.crateApiTypesFulaConfigDefault();

  @override
  int get hashCode =>
      endpoint.hashCode ^
      accessToken.hashCode ^
      timeoutSeconds.hashCode ^
      maxRetries.hashCode ^
      perChunkDownloadTimeoutSeconds.hashCode ^
      bufferedDownloadMaxBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FulaConfig &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          accessToken == other.accessToken &&
          timeoutSeconds == other.timeoutSeconds &&
          maxRetries == other.maxRetries &&
          perChunkDownloadTimeoutSeconds ==
              other.perChunkDownloadTimeoutSeconds &&
          bufferedDownloadMaxBytes == other.bufferedDownloadMaxBytes;
}

/// Result of a get operation with metadata
class GetObjectResult {
  /// Object data
  final Uint8List data;

  /// ETag
  final String etag;

  /// Content type
  final String? contentType;

  /// Size in bytes
  final BigInt size;

  /// Last modified timestamp (Unix epoch seconds)
  final PlatformInt64 lastModified;

  /// User metadata
  final List<MetadataEntry> metadata;

  const GetObjectResult({
    required this.data,
    required this.etag,
    this.contentType,
    required this.size,
    required this.lastModified,
    required this.metadata,
  });

  @override
  int get hashCode =>
      data.hashCode ^
      etag.hashCode ^
      contentType.hashCode ^
      size.hashCode ^
      lastModified.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GetObjectResult &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          etag == other.etag &&
          contentType == other.contentType &&
          size == other.size &&
          lastModified == other.lastModified &&
          metadata == other.metadata;
}

/// Result of a HEAD operation
class HeadResult {
  /// ETag
  final String etag;

  /// Content type
  final String? contentType;

  /// Size in bytes
  final BigInt size;

  /// Last modified timestamp (Unix epoch seconds)
  final PlatformInt64 lastModified;

  /// User metadata
  final List<MetadataEntry> metadata;

  const HeadResult({
    required this.etag,
    this.contentType,
    required this.size,
    required this.lastModified,
    required this.metadata,
  });

  @override
  int get hashCode =>
      etag.hashCode ^
      contentType.hashCode ^
      size.hashCode ^
      lastModified.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeadResult &&
          runtimeType == other.runtimeType &&
          etag == other.etag &&
          contentType == other.contentType &&
          size == other.size &&
          lastModified == other.lastModified &&
          metadata == other.metadata;
}

/// Result of listing objects
class ListObjectsResult {
  /// Objects in the current page
  final List<ObjectInfo> objects;

  /// Common prefixes (for delimiter-based listing)
  final List<String> commonPrefixes;

  /// Whether there are more results
  final bool isTruncated;

  /// Token for fetching next page
  final String? nextToken;

  const ListObjectsResult({
    required this.objects,
    required this.commonPrefixes,
    required this.isTruncated,
    this.nextToken,
  });

  @override
  int get hashCode =>
      objects.hashCode ^
      commonPrefixes.hashCode ^
      isTruncated.hashCode ^
      nextToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListObjectsResult &&
          runtimeType == other.runtimeType &&
          objects == other.objects &&
          commonPrefixes == other.commonPrefixes &&
          isTruncated == other.isTruncated &&
          nextToken == other.nextToken;
}

/// Options for listing objects
class ListOptions {
  /// Prefix filter
  final String? prefix;

  /// Delimiter for hierarchical listing
  final String? delimiter;

  /// Maximum keys to return
  final int? maxKeys;

  /// Continuation token for pagination
  final String? continuationToken;

  const ListOptions({
    this.prefix,
    this.delimiter,
    this.maxKeys,
    this.continuationToken,
  });

  static Future<ListOptions> default_() =>
      RustLib.instance.api.crateApiTypesListOptionsDefault();

  @override
  int get hashCode =>
      prefix.hashCode ^
      delimiter.hashCode ^
      maxKeys.hashCode ^
      continuationToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListOptions &&
          runtimeType == other.runtimeType &&
          prefix == other.prefix &&
          delimiter == other.delimiter &&
          maxKeys == other.maxKeys &&
          continuationToken == other.continuationToken;
}

/// A key-value metadata entry
class MetadataEntry {
  /// Metadata key
  final String key;

  /// Metadata value
  final String value;

  const MetadataEntry({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

/// Obfuscation mode for file name privacy
///
/// Controls how file paths are obfuscated before sending to the server.
/// This affects what the server can learn about your file structure.
enum ObfuscationMode {
  /// Hash the key with a secret prefix (deterministic - same key = same hash)
  /// Allows server-side deduplication but reveals if same file uploaded twice.
  /// Server sees: `e/a7c3f9b2e8d14a6f` (reveals "e/" prefix)
  deterministic,

  /// Random UUID for each upload (non-deterministic)
  /// Maximum privacy but no dedup.
  /// Server sees: `e/random-uuid-here`
  random,

  /// Flat namespace - complete structure hiding (RECOMMENDED)
  ///
  /// Inspired by WNFS and Peergos:
  /// - All keys look like random CID-style hashes
  /// - No prefixes or structure hints
  /// - File tree stored in encrypted index (PrivateForest)
  /// - Server cannot determine folder structure, parent/child relationships
  ///
  /// Server sees: `QmX7a8f3e2d1c9b4a5e6f7d8c9a0b1e2f3a4b5c6d7e8f9`
  flatNamespace,

  /// Preserve path structure but hash filenames
  /// e.g., "/photos/vacation/" + hash(filename)
  /// Allows folder-like organization while hiding filenames.
  /// Server sees: `/photos/vacation/e_a7c3f9b2`
  preserveStructure;

  static Future<ObfuscationMode> default_() =>
      RustLib.instance.api.crateApiTypesObfuscationModeDefault();
}

/// Information about an object
class ObjectInfo {
  /// Object key
  final String key;

  /// Size in bytes
  final BigInt size;

  /// Last modified timestamp (Unix epoch seconds)
  final PlatformInt64 lastModified;

  /// ETag
  final String etag;

  /// Storage class
  final String storageClass;

  const ObjectInfo({
    required this.key,
    required this.size,
    required this.lastModified,
    required this.etag,
    required this.storageClass,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      size.hashCode ^
      lastModified.hashCode ^
      etag.hashCode ^
      storageClass.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ObjectInfo &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          size == other.size &&
          lastModified == other.lastModified &&
          etag == other.etag &&
          storageClass == other.storageClass;
}

/// Object metadata for upload
class ObjectMetadata {
  /// Content type
  final String? contentType;

  /// Cache control header
  final String? cacheControl;

  /// User metadata entries
  final List<MetadataEntry> userMetadata;

  const ObjectMetadata({
    this.contentType,
    this.cacheControl,
    required this.userMetadata,
  });

  static Future<ObjectMetadata> default_() =>
      RustLib.instance.api.crateApiTypesObjectMetadataDefault();

  @override
  int get hashCode =>
      contentType.hashCode ^ cacheControl.hashCode ^ userMetadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ObjectMetadata &&
          runtimeType == other.runtimeType &&
          contentType == other.contentType &&
          cacheControl == other.cacheControl &&
          userMetadata == other.userMetadata;
}

/// Configuration for IPFS pinning service
class PinningConfig {
  /// Pinning service endpoint URL
  final String endpoint;

  /// Authentication token
  final String token;

  const PinningConfig({required this.endpoint, required this.token});

  @override
  int get hashCode => endpoint.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PinningConfig &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          token == other.token;
}

/// Result of a put/upload operation
class PutResult {
  /// ETag of the uploaded object
  final String etag;

  /// Version ID (if versioning enabled)
  final String? versionId;

  const PutResult({required this.etag, this.versionId});

  @override
  int get hashCode => etag.hashCode ^ versionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PutResult &&
          runtimeType == other.runtimeType &&
          etag == other.etag &&
          versionId == other.versionId;
}

/// Details of a rotation failure
class RotationFailure {
  /// Storage key that failed
  final String storageKey;

  /// Error message
  final String error;

  const RotationFailure({required this.storageKey, required this.error});

  @override
  int get hashCode => storageKey.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RotationFailure &&
          runtimeType == other.runtimeType &&
          storageKey == other.storageKey &&
          error == other.error;
}

/// Report from a bucket rotation operation
class RotationReport {
  /// Total objects processed
  final int total;

  /// Objects successfully rotated
  final int rotated;

  /// Objects skipped (already current)
  final int skipped;

  /// Objects that failed rotation
  final int failed;

  /// Details of failures
  final List<RotationFailure> failures;

  const RotationReport({
    required this.total,
    required this.rotated,
    required this.skipped,
    required this.failed,
    required this.failures,
  });

  /// Check if all rotations succeeded
  Future<bool> isSuccess() =>
      RustLib.instance.api.crateApiTypesRotationReportIsSuccess(that: this);

  /// Get success rate as percentage
  Future<double> successRate() =>
      RustLib.instance.api.crateApiTypesRotationReportSuccessRate(that: this);

  @override
  int get hashCode =>
      total.hashCode ^
      rotated.hashCode ^
      skipped.hashCode ^
      failed.hashCode ^
      failures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RotationReport &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          rotated == other.rotated &&
          skipped == other.skipped &&
          failed == other.failed &&
          failures == other.failures;
}

/// Share mode for creating share tokens
enum ShareMode {
  /// Read-only access
  read,

  /// Read and write access
  write,

  /// Time-limited access
  temporal,

  /// Snapshot (point-in-time) access
  snapshot,
}

/// Permissions granted by a share
class SharePermissions {
  /// Can read content
  final bool canRead;

  /// Can write/modify content
  final bool canWrite;

  /// Expiration timestamp (Unix epoch seconds), None = never expires
  final PlatformInt64? expiresAt;

  const SharePermissions({
    required this.canRead,
    required this.canWrite,
    this.expiresAt,
  });

  @override
  int get hashCode => canRead.hashCode ^ canWrite.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SharePermissions &&
          runtimeType == other.runtimeType &&
          canRead == other.canRead &&
          canWrite == other.canWrite &&
          expiresAt == other.expiresAt;
}

/// Progress of an upload operation
class UploadProgress {
  /// Bytes uploaded so far
  final BigInt bytesUploaded;

  /// Total bytes to upload
  final BigInt totalBytes;

  /// Current part number
  final int currentPart;

  /// Total number of parts
  final int totalParts;

  /// Percentage complete (0.0 - 100.0)
  final double percentage;

  const UploadProgress({
    required this.bytesUploaded,
    required this.totalBytes,
    required this.currentPart,
    required this.totalParts,
    required this.percentage,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new progress struct
  static Future<UploadProgress> newInstance({
    required BigInt bytesUploaded,
    required BigInt totalBytes,
    required int currentPart,
    required int totalParts,
  }) => RustLib.instance.api.crateApiTypesUploadProgressNew(
    bytesUploaded: bytesUploaded,
    totalBytes: totalBytes,
    currentPart: currentPart,
    totalParts: totalParts,
  );

  @override
  int get hashCode =>
      bytesUploaded.hashCode ^
      totalBytes.hashCode ^
      currentPart.hashCode ^
      totalParts.hashCode ^
      percentage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadProgress &&
          runtimeType == other.runtimeType &&
          bytesUploaded == other.bytesUploaded &&
          totalBytes == other.totalBytes &&
          currentPart == other.currentPart &&
          totalParts == other.totalParts &&
          percentage == other.percentage;
}
