/// Fula Client SDK
///
/// A Flutter/Dart SDK for Fula decentralized storage with client-side encryption,
/// metadata privacy, and secure file sharing.
///
/// ## Quick Start
///
/// ```dart
/// import 'package:fula_client/fula_client.dart';
///
/// // Create encrypted client
/// final config = FulaConfig(
///   endpoint: 'http://localhost:9000',
///   accessToken: 'your-token',
/// );
///
/// final encConfig = EncryptionConfig(
///   enableMetadataPrivacy: true,
/// );
///
/// final client = await createEncryptedClient(config, encConfig);
///
/// // Upload encrypted file
/// await putFlat(client, 'my-bucket', '/path/file.txt', data, 'text/plain');
///
/// // Download and decrypt
/// final decrypted = await getFlat(client, 'my-bucket', '/path/file.txt');
/// ```
library fula_client;

// Re-export generated bindings (will be generated by flutter_rust_bridge_codegen)
// export 'src/bridge_generated.dart';

// Placeholder exports until bindings are generated
// These will be replaced by the actual generated exports

/// Configuration for connecting to a Fula gateway
class FulaConfig {
  /// Gateway endpoint URL (e.g., "http://localhost:9000")
  final String endpoint;

  /// JWT access token for authentication
  final String? accessToken;

  /// Request timeout in seconds (default: 30)
  final int timeoutSeconds;

  /// Maximum retry attempts (default: 3)
  final int maxRetries;

  const FulaConfig({
    required this.endpoint,
    this.accessToken,
    this.timeoutSeconds = 30,
    this.maxRetries = 3,
  });
}

/// Configuration for client-side encryption
class EncryptionConfig {
  /// Secret key bytes (32 bytes). If null, a new key is generated.
  final List<int>? secretKey;

  /// Enable metadata privacy (obfuscates file names)
  final bool enableMetadataPrivacy;

  /// Obfuscation mode for file names
  final ObfuscationMode obfuscationMode;

  const EncryptionConfig({
    this.secretKey,
    this.enableMetadataPrivacy = true,
    this.obfuscationMode = ObfuscationMode.deterministic,
  });
}

/// Obfuscation mode for file name privacy
enum ObfuscationMode {
  /// Same input always produces same output (allows deduplication)
  deterministic,

  /// Random obfuscation (maximum privacy)
  random,
}

/// Share mode for creating share tokens
enum ShareMode {
  /// Read-only access
  read,

  /// Read and write access
  write,

  /// Time-limited access
  temporal,

  /// Snapshot (point-in-time) access
  snapshot,
}

// Note: Full API will be available once flutter_rust_bridge_codegen generates
// the bindings from crates/fula-flutter/src/api/mod.rs
//
// Available APIs after generation:
// - createClient, createEncryptedClient
// - listBuckets, createBucket, deleteBucket
// - putObject, getObject, deleteObject, listObjects
// - putEncrypted, getDecrypted, listDecrypted
// - putFlat, getFlat, deleteFlat, listDirectory
// - createShareToken, acceptShare, getWithShare
// - createRotationManager, rotateBucket
// - startMultipart, uploadPart, completeMultipart
// - exportSecretKey, getPublicKey
