// Web platform implementation for fula_client
//
// This file handles WASM loading and initialization for Flutter Web.
// The WASM module is loaded asynchronously when the plugin is first used.

import 'dart:async';
import 'dart:js_interop';

import 'package:flutter_web_plugins/flutter_web_plugins.dart';
import 'package:web/web.dart' as web;

/// Web implementation of the Fula Client plugin.
///
/// This class handles loading the WASM module and exposing the Rust
/// functions to Dart via JavaScript interop.
class FulaClientWeb {
  static bool _initialized = false;
  static Completer<void>? _initCompleter;

  /// Registers this class as the default instance of [FulaClientPlatform].
  static void registerWith(Registrar registrar) {
    // Plugin registration for Flutter Web
  }

  /// Initialize the WASM module.
  ///
  /// This loads the WASM binary and JavaScript glue code.
  /// Must be called before any other Fula functions.
  static Future<void> initialize() async {
    if (_initialized) return;

    if (_initCompleter != null) {
      return _initCompleter!.future;
    }

    _initCompleter = Completer<void>();

    try {
      // Load the WASM module
      await _loadWasmModule();
      _initialized = true;
      _initCompleter!.complete();
    } catch (e) {
      _initCompleter!.completeError(e);
      _initCompleter = null;
      rethrow;
    }
  }

  /// Check if the WASM module is loaded.
  static bool get isInitialized => _initialized;

  /// Load the WASM module from the assets.
  static Future<void> _loadWasmModule() async {
    // The WASM and JS files should be placed in web/
    // They are generated by wasm-pack during the build process
    // Note: The JS file is named after the Rust crate (fula_flutter)

    final script = web.HTMLScriptElement()
      ..src = 'fula_flutter.js'
      ..type = 'module';

    final completer = Completer<void>();

    script.onload = ((web.Event event) {
      // Call the init function exported by wasm-bindgen
      _initWasm().toDart.then((_) {
        completer.complete();
      }).catchError((e) {
        completer.completeError('Failed to initialize WASM: $e');
      });
    }).toJS;

    script.onerror = ((web.Event event) {
      completer.completeError('Failed to load WASM script');
    }).toJS;

    web.document.head!.append(script);

    return completer.future;
  }
}

/// JS interop for the WASM init function
@JS('__wbg_init')
external JSPromise<JSAny?> _initWasm();
